/* ─── TOEIC DATA ─────────────────────────────────────── */
const TOEIC_PARTS={
  p2:[
    {en:'This is a picture taken at a park.',ko:'이 사진은 공원에서 찍힌 사진이다.'},
    {en:'This is a picture taken at an office.',ko:'이 사진은 사무실에서 찍힌 사진이다.'},
    {en:'This is a picture taken at a restaurant.',ko:'이 사진은 레스토랑에서 찍힌 사진이다.'},
    {en:'This is a picture taken at a library.',ko:'이 사진은 도서관에서 찍힌 사진이다.'},
    {en:'This is a picture taken indoors.',ko:'이 사진은 실내에서 찍힌 사진이다.'},
    {en:'This is a picture taken outdoors.',ko:'이 사진은 실외에서 찍힌 사진이다.'},
    {en:'This is a picture taken at a laboratory.',ko:'이 사진은 실험실에서 찍힌 사진이다.'},
    {en:'This is a picture taken at a clothing store.',ko:'이 사진은 옷 가게에서 찍힌 사진이다.'},
    {en:'This is a picture taken at a warehouse.',ko:'이 사진은 창고에서 찍힌 사진이다.'},
    {en:'This is a picture taken at a café.',ko:'이 사진은 카페에서 찍힌 사진이다.'},
    {en:'This is a picture taken at a cafeteria.',ko:'이 사진은 구내 식당에서 찍힌 사진이다.'},
    {en:'This is a picture taken on a street.',ko:'이 사진은 길 위에서 찍힌 사진이다.'},
    {en:'This is a picture taken at a construction site.',ko:'이 사진은 공사장에서 찍힌 사진이다.'},
    {en:'In the foreground of the picture, I can see a lot of office supplies on the desk.',ko:'사진의 전면에서 나는 책상 위에 올려진 많은 사무용품들을 볼 수 있다.'},
    {en:'In the middle of the picture, there is a fountain.',ko:'사진의 중심에 분수대가 있다.'},
    {en:'On the left side of the picture, there is a sidewalk.',ko:'사진의 왼쪽에 인도가 있다.'},
    {en:'On the right side of the picture, there is a large window.',ko:'사진의 오른쪽에 큰 창문이 있다.'},
    {en:'In the background of the picture, I can see many buildings and trees.',ko:'사진의 배경에서 나는 많은 건물들과 나무들을 볼 수 있다.'},
    {en:'Most of them are wearing formal clothes.',ko:'그들 중 대부분은 정장을 입고 있다.'},
    {en:'Some of them are wearing casual clothes.',ko:'그들 중 일부는 캐주얼을 입고 있다.'},
    {en:'She is looking into a bag.',ko:'그녀는 가방 안을 들여다 보고 있다.'},
    {en:'He is helping customers.',ko:'그는 고객들을 돕고 있다.'},
    {en:'She is walking a dog.',ko:'그녀는 강아지를 산책 시키고 있다.'},
    {en:'He is holding something.',ko:'그는 무언가를 들고 있다.'},
    {en:'She is looking at a menu.',ko:'그녀는 메뉴판을 보고 있다.'},
    {en:'He is writing something down.',ko:'그는 무언가를 쓰고 있다.'},
    {en:'She is holding a document.',ko:'그녀는 서류를 들고 있다.'},
    {en:'She is holding a shopping bag.',ko:'그녀는 쇼핑백을 들고 있다.'},
    {en:'He is reaching for an item.',ko:'그는 물건을 집으려고 손을 뻗고 있다.'},
    {en:'She is looking at a smartphone.',ko:'그녀는 스마트폰을 보고 있다.'},
    {en:'He is drinking some water.',ko:'그는 물을 마시고 있다.'},
    {en:'She is cooking.',ko:'그녀는 요리를 하고 있다.'},
    {en:'He is making a presentation.',ko:'그는 발표를 하고 있다.'},
    {en:'She is serving food to customers.',ko:'그녀는 음식을 고객들에게 서빙하고 있다.'},
    {en:'He is using a tablet PC.',ko:'그는 태블릿 PC를 사용하고 있다.'},
    {en:'She is holding a cup.',ko:'그녀는 컵을 들고 있다.'},
    {en:'She is eating some food.',ko:'그녀는 음식을 먹고 있다.'},
    {en:'He is riding a bicycle.',ko:'그는 자전거를 타고 있다.'},
    {en:'She is talking on the phone.',ko:'그녀는 전화통화를 하고 있다.'},
    {en:'She is working on a computer.',ko:'그녀는 컴퓨터로 일하고 있다.'},
    {en:'He is working on a laptop.',ko:'그는 노트북으로 일하고 있다.'},
    {en:'He is loading a box into a truck.',ko:'그는 트럭에 박스를 싣고 있다.'},
    {en:'He is cleaning with a vacuum.',ko:'그는 청소기로 청소를 하고 있다.'},
    {en:'He is pushing a cart.',ko:'그는 카트를 밀고 있다.'},
    {en:'They are walking down the stairs.',ko:'그들은 계단을 내려오고 있다.'},
    {en:'They are crossing the street.',ko:'그들은 길을 건너고 있다.'},
    {en:'They are having a conversation.',ko:'그들은 대화를 하고 있다.'},
    {en:'They are reading a document.',ko:'그들은 문서를 읽고 있다.'},
    {en:'They are sitting on a bench.',ko:'그들은 벤치에 앉아있다.'},
    {en:'They are using a copy machine.',ko:'그들은 복사기를 이용하고 있다.'},
    {en:'They are talking to each other.',ko:'그들은 서로 얘기하고 있다.'},
    {en:'They are playing musical instruments.',ko:'그들은 악기를 연주하고 있다.'},
    {en:'They are wearing uniforms.',ko:'그들은 유니폼을 입고 있다.'},
    {en:'They are sitting on the grass.',ko:'그들은 잔디 위에 앉아있다.'},
    {en:'They are using computers.',ko:'그들은 컴퓨터를 이용하고 있다.'},
    {en:'They are sitting at a table.',ko:'그들은 테이블에 앉아있다.'},
    {en:'They are having a video conference.',ko:'그들은 화상회의를 하고 있다.'},
    {en:'They are having a meeting.',ko:'그들은 회의를 하고 있다.'},
    {en:'She is pointing at the screen.',ko:'그녀는 화면을 가리키는 중이다.'},
    {en:'He is carrying a box.',ko:'그는 박스를 운반 중이다.'},
    {en:'They are sitting under the parasol.',ko:'그들은 파라솔 밑에 앉아있다.'},
    {en:'They are having a picnic.',ko:'그들은 소풍을 하고 있다.'},
    {en:'She is wearing white pants.',ko:'그녀는 흰색 바지를 입고 있다.'},
    {en:'She is wearing sunglasses.',ko:'그녀는 선글라스를 쓰고 있다.'},
    {en:'He is wearing glasses.',ko:'그는 안경을 쓰고 있다.'},
    {en:'He is wearing a striped shirt.',ko:'그는 줄무늬 셔츠를 입고 있다.'},
    {en:'He is wearing jeans.',ko:'그는 청바지를 입고 있다.'},
    {en:'Products are displayed on the shelves.',ko:'제품들이 진열대 위에 진열되어 있다.'},
    {en:'I can see many books on the bookshelves.',ko:'나는 책장에 많은 책들을 볼 수 있다.'},
    {en:'Items are arranged on the shelves.',ko:'물품들이 선반 위에 정리되어 있다.'},
    {en:'Overall, it seems like they are busy.',ko:'전반적으로 그들은 바쁜 것 같다.'},
    {en:'Overall, it seems like a beautiful sunny day.',ko:'전반적으로 아름다운 화창한 날씨인 것 같다.'},
    {en:'Overall, it seems like a peaceful day.',ko:'전반적으로 평화로운 날 같다.'},
  ],
  p3:[
    {en:'It relieves my stress. I\'m stressed out these days. So, I need this.',ko:'이것은 나의 스트레스를 풀어준다. 나는 요즘 스트레스를 많이 받았다. 그래서 이것이 필요하다.'},
    {en:'It\'s cheaper, so I can save money.',ko:'이것은 더 싸서 돈을 절약할 수 있다.'},
    {en:'The price is reasonable.',ko:'가격이 저렴하다.'},
    {en:'It\'s faster, so I can save time.',ko:'이것은 더 빨라서 시간을 절약할 수 있다.'},
    {en:'I can get a lot of useful information from my friends.',ko:'나는 친구들에게 많은 유용한 정보를 얻을 수 있다.'},
    {en:'I can get a lot of useful information from books.',ko:'나는 책에서 많은 유용한 정보를 얻을 수 있다.'},
    {en:'I can get a lot of useful information on the Internet.',ko:'나는 인터넷에서 많은 유용한 정보를 얻을 수 있다.'},
    {en:'It\'s more reliable, so the information is more trustworthy.',ko:'이것은 더 믿을 만해서 정보가 더 신뢰가 간다.'},
    {en:'I can get information anytime anywhere on my smartphone.',ko:'나는 정보를 언제 어디서나 내 스마트폰으로 얻을 수 있다.'},
    {en:'It is more personal, and builds a closer relationship.',ko:'이것은 더 개인적이고 더 밀접한 인간관계를 쌓을 수 있다.'},
    {en:'It causes less misunderstanding.',ko:'이것은 오해를 덜 불러일으킨다.'},
    {en:'It\'s my favorite thing to do.',ko:'이것은 내가 가장 좋아하는 일이다.'},
    {en:'It makes me happy, and I can forget about my worries.',ko:'이것은 나를 행복하게 해주고 나는 걱정 근심을 잊을 수 있다.'},
    {en:'It has great facilities.',ko:'이것은 좋은 시설을 가지고 있다.'},
    {en:'It\'s a well-liked place so people love it.',ko:'이곳은 인기 있는 곳이라 사람들이 좋아한다.'},
    {en:'I\'m a student so my budget is tight.',ko:'나는 학생이라 예산이 빠듯하다.'},
    {en:'I can\'t afford to buy expensive things.',ko:'나는 비싼 것을 살 여유가 없다.'},
    {en:'I don\'t want to waste too much money on that.',ko:'나는 그것에 지나치게 많은 돈을 쓰고 싶지 않다.'},
    {en:'It\'s a waste of money.',ko:'이것은 돈 낭비다.'},
    {en:'I\'m a student and I\'m so busy with my school work.',ko:'나는 학생이다. 그래서 학업에 바쁘다.'},
    {en:'I don\'t have much time.',ko:'나는 시간이 많이 없다.'},
    {en:'I don\'t want to waste too much time on that.',ko:'나는 그것에 지나치게 많은 시간을 낭비하기 싫다.'},
    {en:'It\'s a waste of time.',ko:'이것은 시간 낭비다.'},
    {en:'It\'s more fun and entertaining, so I don\'t get bored.',ko:'이것은 더 재밌고 즐거움을 주는 일이다. 그래서 나는 지루해지지 않는다.'},
    {en:'I think it\'s more fun to do things in a group.',ko:'나는 같이 하는 것이 더 재미있다고 생각한다.'},
    {en:'I can meet new people and make friends.',ko:'나는 새로운 사람을 만날 수 있고 친구를 만들 수 있다.'},
    {en:'I feel more comfortable and I can focus better.',ko:'나는 더 편안함을 느끼고 더 잘 집중할 수 있다.'},
    {en:'I don\'t have to waste time waiting for other people.',ko:'나는 다른 사람들을 기다리느라 시간을 낭비할 필요가 없다.'},
    {en:'I feel more comfortable at home.',ko:'나는 집에서 더 편안함을 느낀다.'},
    {en:'I can save time because I don\'t have to waste time going out.',ko:'나는 시간을 절약할 수 있다. 왜냐하면 나는 밖에 나가느라 시간을 낭비할 필요가 없기 때문이다.'},
    {en:'It\'s very necessary for me.',ko:'이것은 나에게 매우 필요한 것이다.'},
    {en:'I frequently use it.',ko:'나는 그것을 자주 이용한다.'},
    {en:'It makes me happy and I can have a great experience.',ko:'이것은 나를 행복하게 해주고 나는 좋은 경험을 할 수 있다.'},
    {en:'It\'s a popular item so people will love it.',ko:'이것은 인기있는 아이템인지라 사람들이 좋아할 것이다.'},
    {en:'It has sentimental value.',ko:'이것은 의미가 깊다.'},
    {en:'I like to try new things.',ko:'나는 새로운 것을 시도해 보는 것을 좋아한다.'},
    {en:'It\'s a good gift.',ko:'이것은 좋은 선물이다.'},
    {en:'It\'s part of my routine.',ko:'이것은 내 일상의 일부이다.'},
    {en:'It\'s my habit.',ko:'이것은 내 습관이다.'},
    {en:'It\'s cheaper and faster.',ko:'이것은 더 싸고 빠르다.'},
    {en:'It\'s very convenient and useful.',ko:'이것은 매우 편리하고 유용하다.'},
    {en:'It\'s very helpful for me.',ko:'이것은 나에게 매우 도움이 된다.'},
  ],
  p4:[
    {en:'The conference will be held on June 20th at Hilton Hotel.',ko:'컨퍼런스가 6월 20일 힐튼호텔에서 개최될 예정입니다.'},
    {en:'The meeting will start at 9:00 am.',ko:'미팅은 오전 9시에 시작할 것입니다.'},
    {en:'The seminar will finish at 5:00 pm.',ko:'세미나는 오후 5시에 끝날 것입니다.'},
    {en:'No, I\'m afraid that you have the wrong information. Actually, the registration and coffee session will start at 9:00 a.m.',ko:'아니요, 유감스럽게도 잘못 알고 계십니다. 사실 등록 및 커피타임은 오전 9시에 시작될 것입니다.'},
    {en:'You will depart from San Francisco at 10 am on American Air 105.',ko:'당신은 10시에 아메리칸 에어 105기를 타고 샌프란시스코에서 출발할 것입니다.'},
    {en:'You will arrive in Los Angeles at 3 pm.',ko:'당신은 로스앤젤레스에 오후 3시에 도착할 것입니다.'},
    {en:'You will take Korean Air 105.',ko:'당신은 대한항공 105기를 탈 것입니다.'},
    {en:'You will stay at Glen Hotel.',ko:'당신은 글렌호텔에 머무를 것입니다.'},
    {en:'You will give a speech at the annual conference.',ko:'당신은 연례 컨퍼런스에서 스피치를 할 것입니다.'},
    {en:'You will lead a workshop on social media marketing.',ko:'당신은 소셜 미디어 마케팅에 관한 워크숍을 이끌 것입니다.'},
    {en:'You will attend a seminar on business development.',ko:'당신은 비즈니스 개발에 관한 세미나에 참석할 것입니다.'},
    {en:'There was supposed to be a meeting but it has been canceled.',ko:'회의가 있기로 되어 있었으나 취소되었습니다.'},
    {en:'There was supposed to be a seminar but it has been postponed.',ko:'세미나가 있기로 되어 있었으나 연기되었습니다.'},
    {en:'There was supposed to be a workshop but it has been rescheduled to Friday.',ko:'워크숍이 있기로 되어 있었으나 금요일로 스케쥴이 조정되었습니다.'},
    {en:'She got a Master\'s degree in Design from Vancouver Art University in 2010.',ko:'그녀는 벤쿠버 예술 대학교에서 2010년에 디자인 전공으로 석사 학위를 취득했습니다.'},
    {en:'From 2015 to 2017, she worked at Jasper Fashion Magazine as a director.',ko:'2015년부터 2017년까지, 그녀는 재스퍼 패션 잡지사에서 이사로 일했습니다.'},
    {en:'From 2017 up to now, she has worked at Toronto Fashion Magazine as a chief editor.',ko:'2017년부터 지금까지, 그녀는 토론토 패션잡지사에서 편집장으로 일해 오고 있습니다.'},
    {en:'I think he is qualified because he has experience in education.',ko:'제 생각에 그는 자격 요건이 갖춰진 지원자입니다. 왜냐하면 그는 교육 관련 경험이 있기 때문입니다.'},
    {en:'He is fluent in Spanish.',ko:'그는 스페인어를 유창하게 구사합니다.'},
    {en:'She is certified in pilates.',ko:'그녀는 필라테스 자격증이 있습니다.'},
    {en:'You will interview Jessica Anderson at 9:00 a.m.',ko:'당신은 제시카 앤더슨과 오전 9시에 면접을 볼 것입니다.'},
    {en:'She has 5 years of experience.',ko:'그녀는 5년의 업무경력이 있습니다.'},
    {en:'He is applying for the editor position.',ko:'그는 편집장직에 지원하고 있습니다.'},
    {en:'You have to pay 20 dollars for the oil painting class.',ko:'오일 페인팅 수업은 20달러입니다.'},
    {en:'You should register by January 3rd.',ko:'1월 3일까지 등록하셔야 합니다.'},
    {en:'If you are a member, it\'s free. If you are not a member, it\'s 20 dollars.',ko:'당신이 회원이라면 무료이지만 비회원이라면 20달러를 지불하셔야 합니다.'},
    {en:'It\'s for beginners.',ko:'이것은 초급자들을 위한 강좌입니다.'},
    {en:'Sean Kim will teach the cooking class.',ko:'션 킴 강사가 요리 수업을 지도할 것입니다.'},
    {en:'Jennifer Huston will teach a class on French Art History.',ko:'제니퍼 휴스턴 강사가 프랑스 예술사에 관한 수업을 지도할 예정입니다.'},
  ],
  p5:[
    {en:'They can learn new things.',ko:'그들은 새로운 것들을 배울 수 있다.'},
    {en:'They can meet new people and expand their network.',ko:'그들은 새로운 사람을 만나고 인맥을 넓힐 수 있다.'},
    {en:'They can have a lot of new experience and broaden their perspective.',ko:'그들은 많은 것을 경험하고 그들의 견문을 넓힐 수 있다.'},
    {en:'They can\'t make good decisions because they are not mature enough.',ko:'그들은 좋은 결정을 하지 못하는데 왜냐하면 그들은 아직 충분히 성숙하지 못했기 때문이다.'},
    {en:'They will be distracted.',ko:'그들은 집중을 못하게 될 것이다.'},
    {en:'They can\'t focus on their studies.',ko:'그들은 그들의 학업에 집중할 수 없다.'},
    {en:'They can\'t get good grades at school.',ko:'그들은 학교에서 좋은 성적을 받을 수 없다.'},
    {en:'They will fall behind in class.',ko:'그들은 학업이 뒤쳐질 것이다.'},
    {en:'They can\'t work efficiently.',ko:'그들은 효율적으로 일할 수 없다.'},
    {en:'They can save money.',ko:'그들은 돈을 절약할 수 있다.'},
    {en:'The cost of living is too high.',ko:'생활비가 너무 비싸다.'},
    {en:'They can\'t make a living.',ko:'그들은 먹고 살기가 힘들다.'},
    {en:'I can get a higher salary.',ko:'나는 더 높은 급여를 받을 수 있다.'},
    {en:'The cost of tuition is too expensive.',ko:'수업료가 너무 비싸다.'},
    {en:'It\'s a waste of money.',ko:'돈 낭비다.'},
    {en:'That\'s a good investment because it makes lives better.',ko:'그것은 좋은 투자인데 왜냐하면 삶을 더 낫게 만들어준다.'},
    {en:'They can focus better.',ko:'그들은 더 잘 집중할 수 있다.'},
    {en:'They will not be distracted by others.',ko:'그들은 다른 사람들에게 방해받지 않을 것이다.'},
    {en:'They can set their own schedule.',ko:'그들은 그들의 스케쥴을 정할 수 있다.'},
    {en:'They can have more freedom.',ko:'그들은 더 자유로울 수 있다.'},
    {en:'They feel more comfortable.',ko:'그들은 더 편안함을 느낀다.'},
    {en:'It\'s fun and entertaining.',ko:'이것은 재밌고 즐거움을 준다.'},
    {en:'They can get information and share it with other people.',ko:'그들은 정보를 얻고 다른 사람과 공유할 수 있다.'},
    {en:'It feels more like a family.',ko:'더 가족처럼 느껴진다.'},
    {en:'They can get a lot of useful information on the Internet.',ko:'그들은 많은 유용한 정보를 인터넷에서 얻을 수 있다.'},
    {en:'They can communicate with their friends anytime anywhere on their smartphones.',ko:'그들은 스마트폰으로 언제 어디서나 친구들과 소통할 수 있다.'},
    {en:'It\'s faster and convenient.',ko:'이것은 더 빠르고 편리하다.'},
    {en:'There is a lot of inaccurate information on the Internet so it\'s not reliable.',ko:'인터넷에는 많은 부정확한 정보가 있어서 믿을 만하지가 않다.'},
    {en:'I can get responses right away.',ko:'나는 즉각적인 답변을 받을 수 있다.'},
    {en:'I can understand the feeling of the speaker more accurately.',ko:'나는 화자의 감정을 더 정확하게 이해할 수 있다.'},
    {en:'They can make a friendly work atmosphere.',ko:'그들은 좋은 업무 분위기를 만들 수 있다.'},
    {en:'They can communicate with others better.',ko:'그들은 다른 사람들과 더 잘 소통할 수 있다.'},
    {en:'They can be good team players and make good relationships with others.',ko:'그들은 좋은 팀플레이어가 될 수 있고 다른 사람들과 좋은 관계를 맺을 수 있다.'},
    {en:'They can have a good reputation.',ko:'그들은 좋은 평판을 가질 수 있다.'},
    {en:'They can be very influential.',ko:'그들은 매우 영향력 있을 수 있다.'},
    {en:'They can motivate others.',ko:'그들은 다른 사람들을 동기부여해줄 수 있다.'},
    {en:'Everything is always changing and there is a lot of competition.',ko:'모든 것이 급변하고 경쟁이 치열하다.'},
    {en:'They face a lot of challenges and difficulties.',ko:'그들은 많은 도전과 어려움을 직면하게 된다.'},
    {en:'They have a lot of experience and knowledge.',ko:'그들은 많은 경험과 지식을 가지고 있다.'},
    {en:'Employees can work more efficiently and productively.',ko:'직원들은 더 효율적 생산적으로 일할 수 있다.'},
    {en:'Employees can be more satisfied with their jobs.',ko:'직원들은 그들의 직장에 더 만족할 수 있다.'},
    {en:'It can make a better work environment.',ko:'이것은 더 나은 업무 환경을 만든다.'},
    {en:'Customers will feel satisfied and remain loyal.',ko:'고객들은 만족할 것이고 고객충성도를 유지할 것이다.'},
    {en:'It will attract more customers.',ko:'이것은 더 많은 고객을 끌어들일 것이다.'},
    {en:'The business will be more successful.',ko:'업체가 더 성공할 것이다.'},
    {en:'It relieves their stress and they can relax.',ko:'이것은 그들의 스트레스를 풀어주고 그들은 쉴 수 있다.'},
    {en:'It is good for their physical and mental health.',ko:'이것은 그들의 신체적 정신적 건강에 좋다.'},
    {en:'Pollution is a serious issue these days.',ko:'환경오염은 요즘 매우 심각한 문제다.'},
    {en:'It can make a cleaner environment.',ko:'이것은 더 깨끗한 환경을 만들 수 있다.'},
    {en:'We will be able to protect the environment.',ko:'우리는 환경을 보호할 수 있을 것이다.'},
  ]
};

/* ─── CUSTOM CARD DATA ───────────────────────────────── */
const CUSTOM_CARDS=[
  {
    id:'mistake',emoji:'🚨',title:'매번 틀린 단어',sub:'틀리기 쉬운 철자 주의!',priority:'1순위',pClass:'p1',
    type:'mistake', // special quiz type
    items:[
      {wrong:'things',correct:'thing',note:'s 절대 금지!'},
      {wrong:'indoor',correct:'indoors',note:'s 꼭 붙이기!'},
      {wrong:'outdoor',correct:'outdoors',note:'s 꼭 붙이기!'},
      {wrong:'back ground',correct:'background',note:'붙여쓰기!'},
      {wrong:'coffe',correct:'coffee',note:'e 두 개!'},
      {wrong:'carring',correct:'carrying',note:'r 두 개!'},
      {wrong:'threestrees',correct:'trees',note:'나무! three 아님'},
      {wrong:'enjoynablee',correct:'enjoyable',note:'철자 주의'},
      {wrong:'confortable',correct:'comfortable',note:'편안한, careful ❌'},
    ]
  },
  {
    id: 'tos_and_daily_core_140',
    emoji: '🎯',
    title: '토스 시험 & 현지 일상 필수 단어 140',
    sub: '토스 파트2~5 기출 어휘 + 현지 중학생 일상 필수 단어 통합본',
    priority: '통합필수',
    pClass: 'p1',
    type: 'word',
    words: [
      /* ── 1. Part 2 사진 묘사 (동작·상태·배경) ── */
      {word: 'stroll', meaning: '한가롭게 거닐다, 산책하다'},
      {word: 'browse', meaning: '(가게 상품을) 둘러보다'},
      {word: 'lean against', meaning: '~에 기대다'},
      {word: 'reach for', meaning: '(물건을 잡으려고) 손을 뻗다'},
      {word: 'stack', meaning: '차곡차곡 쌓다, 포개다'},
      {word: 'display', meaning: '진열하다, 전시하다'},
      {word: 'occupy', meaning: '(자리·공간을) 차지하다'},
      {word: 'board', meaning: '(비행기·기차 등에) 탑승하다'},
      {word: 'inspect', meaning: '면밀히 살펴보다, 점검하다'},
      {word: 'distribute', meaning: '나누어 주다, 배포하다'},
      {word: 'applaud', meaning: '박수를 치다'},
      {word: 'gather', meaning: '모이다, 모으다'},
      {word: 'pavement', meaning: '포장도로, 인도'},
      {word: 'intersection', meaning: '교차로, 사거리'},
      {word: 'pedestrian', meaning: '보행자'},
      {word: 'countertop', meaning: '(주방·가게 등의) 조리대, 작업대'},
      {word: 'railing', meaning: '난간, 안전 손잡이'},
      {word: 'awning', meaning: '(가게 차양) 천막'},
      {word: 'overgrown', meaning: '(풀·나무 등이) 무성한'},
      {word: 'scaffolding', meaning: '(공사장) 비계, 임시 가설물'},

      /* ── 2. Part 3 일상 질문 & 여가 (취미·쇼핑·외식) ── */
      {word: 'frequently', meaning: '자주, 빈번하게'},
      {word: 'affordable', meaning: '가격이 알맞은, 감당할 수 있는'},
      {word: 'convenient', meaning: '편리한, 사용하기 쉬운'},
      {word: 'atmosphere', meaning: '(장소의) 분위기'},
      {word: 'reasonable', meaning: '(가격이) 타당한, 적당한'},
      {word: 'preference', meaning: '선호, 더 좋아함'},
      {word: 'relieve', meaning: '(스트레스·통증을) 완화하다'},
      {word: 'ingredient', meaning: '(음식 요리의) 재료'},
      {word: 'recommendation', meaning: '추천'},
      {word: 'commute', meaning: '통근하다, 출퇴근길'},
      {word: 'nearby', meaning: '가까운, 근처의'},
      {word: 'facility', meaning: '시설, 편의 시설'},
      {word: 'membership', meaning: '회원 자격, 회원권'},
      {word: 'recharge', meaning: '(휴식으로) 재충전하다'},
      {word: 'accessible', meaning: '접근하기 쉬운, 이용이 편리한'},
      {word: 'entertaining', meaning: '재미있는, 유쾌한'},
      {word: 'routine', meaning: '정기적인 일과, 판에 박힌 일'},
      {word: 'discount', meaning: '할인'},
      {word: 'durable', meaning: '내구성이 있는, 오래가는'},
      {word: 'versatile', meaning: '다용도의, 다재다능한'},

      /* ── 3. Part 4 일정표 & 비즈니스 공지 ── */
      {word: 'postpone', meaning: '연기하다, 미루다'},
      {word: 'reschedule', meaning: '일정을 다시 잡다'},
      {word: 'cancel', meaning: '취소하다'},
      {word: 'conduct', meaning: '(업무·조사 등을) 수행하다, 진행하다'},
      {word: 'keynote', meaning: '(컨퍼런스 등의) 기조연설'},
      {word: 'registration', meaning: '등록, 참가 신청'},
      {word: 'participant', meaning: '참가자'},
      {word: 'fee', meaning: '요금, 수수료'},
      {word: 'session', meaning: '(회의·수업 등의) 시간, 세션'},
      {word: 'banquet', meaning: '연회, 만찬'},
      {word: 'annual', meaning: '매년의, 연례의'},
      {word: 'applicant', meaning: '지원자'},
      {word: 'qualification', meaning: '자격 요건, 지원 자격'},
      {word: 'fluent', meaning: '유창한, 능숙한'},
      {word: 'itinerary', meaning: '여행/출장 일정표'},
      {word: 'certificate', meaning: '자격증, 증명서'},
      {word: 'director', meaning: '이사, 책임자, 부장'},
      {word: 'relocate', meaning: '(사무실·거주지를) 이전하다'},
      {word: 'available', meaning: '시간이 있는, 이용 가능한'},
      {word: 'confirm', meaning: '확인하다, 확정하다'},

      /* ── 4. Part 5 업무·인사·효율 의견 제시 ── */
      {word: 'productive', meaning: '생산적인'},
      {word: 'efficient', meaning: '효율적인'},
      {word: 'collaborate', meaning: '협력하다, 공동 작업하다'},
      {word: 'distract', meaning: '(집중을) 방해하다, 산만하게 하다'},
      {word: 'flexible', meaning: '유연한, 융통성 있는'},
      {word: 'broaden', meaning: '(시야·견문을) 넓히다'},
      {word: 'perspective', meaning: '관점, 시각, 견문'},
      {word: 'motivate', meaning: '동기를 부여하다'},
      {word: 'morale', meaning: '(팀·직원의) 사기, 의욕'},
      {word: 'feedback', meaning: '피드백, 의견 반영'},
      {word: 'reputation', meaning: '평판, 명성'},
      {word: 'priority', meaning: '우선순위'},
      {word: 'workload', meaning: '업무량'},
      {word: 'achievement', meaning: '성취, 달성한 성과'},
      {word: 'incentive', meaning: '장려책, 인센티브'},
      {word: 'cooperation', meaning: '협조, 협동'},
      {word: 'resolve', meaning: '(문제·갈등을) 해결하다'},
      {word: 'satisfaction', meaning: '만족도'},
      {word: 'overtime', meaning: '초과 근무, 야근'},
      {word: 'deadline', meaning: '마감 기한'},

      /* ── 5. Part 5 고객·사회 이슈 & 문제 해결 ── */
      {word: 'inconvenience', meaning: '불편, 폐'},
      {word: 'apologize', meaning: '사과하다'},
      {word: 'compensation', meaning: '보상, 배상금'},
      {word: 'alternative', meaning: '대안, 대체 방안'},
      {word: 'malfunction', meaning: '(기기·장비의) 오작동, 고장'},
      {word: 'shortage', meaning: '부족, 결핍'},
      {word: 'urgent', meaning: '긴급한, 다급한'},
      {word: 'reliable', meaning: '믿을 수 있는, 신뢰할 만한'},
      {word: 'inaccurate', meaning: '부정확한, 오류가 있는'},
      {word: 'loyal', meaning: '충성스러운, 단골의'},
      {word: 'attract', meaning: '(고객·관심을) 끌어모으다'},
      {word: 'investment', meaning: '투자'},
      {word: 'profitable', meaning: '수익성이 높은, 이익이 되는'},
      {word: 'pollute', meaning: '오염시키다'},
      {word: 'protect', meaning: '보호하다, 지키다'},
      {word: 'conserve', meaning: '(에너지·자원을) 아끼다, 보존하다'},
      {word: 'disposable', meaning: '일회용의'},
      {word: 'renewable', meaning: '재생 가능한'},
      {word: 'competitive', meaning: '경쟁력 있는, 치열한'},
      {word: 'strategy', meaning: '전략, 방안'},

      /* ── 6. 현지 일상 필수 감정 & 상태 표현 ── */
      {word: 'exhausted', meaning: '기진맥진한, 완전히 지친'},
      {word: 'drained', meaning: '진이 다 빠진, 에너지가 고갈된'},
      {word: 'frustrated', meaning: '답답한, 뜻대로 안 돼 짜증 나는'},
      {word: 'awkward', meaning: '어색한, 곤란한'},
      {word: 'relieved', meaning: '안도하는, 다행으로 여기는'},
      {word: 'hectic', meaning: '눈코 뜰 새 없이 바쁜, 정신없는'},
      {word: 'clueless', meaning: '전혀 감을 못 잡는, 아무것도 모르는'},
      {word: 'decent', meaning: '꽤 괜찮은, 수준이 나쁘지 않은'},
      {word: 'messy', meaning: '지저분한, 어질러진'},
      {word: 'spotless', meaning: '먼지 하나 없이 아주 깨끗한'},
      {word: 'picky', meaning: '입맛이나 취향이 까다로운'},
      {word: 'generous', meaning: '너그러운, 후한'},
      {word: 'spontaneous', meaning: '즉흥적인, 계획 없는'},
      {word: 'skeptical', meaning: '의심 많은, 회의적인'},
      {word: 'clumsy', meaning: '손재주가 없거나 칠칠치 못한'},
      {word: 'hilarious', meaning: '빵 터질 정도로 아주 웃긴'},
      {word: 'stuffy', meaning: '(실내 공기가) 답답한, 탁한'},
      {word: 'cozy', meaning: '아늑하고 편안한'},
      {word: 'overwhelming', meaning: '감당하기 벅찬, 압도적인'},
      {word: 'craving', meaning: '(특정 음식이) 몹시 땡김, 갈망'},

      /* ── 7. 현지 일상 필수 행동 & 소통 동사 ── */
      {word: 'interrupt', meaning: '말을 끊다, 방해하다'},
      {word: 'procrastinate', meaning: '할 일을 미루다, 늑장 부리다'},
      {word: 'distract', meaning: '주의를 딴 데로 돌리다, 산만하게 하다'},
      {word: 'tolerate', meaning: '참다, 견디다'},
      {word: 'convince', meaning: '설득하다, 납득시키다'},
      {word: 'assume', meaning: '추정하다, 당연히 그럴 거라고 생각하다'},
      {word: 'hesitate', meaning: '망설이다, 주저하다'},
      {word: 'complain', meaning: '불평하다, 투덜거리다'},
      {word: 'recharge', meaning: '(휴식을 통해) 재충전하다'},
      {word: 'catch up', meaning: '밀린 이야기나 일을 따라잡다'},
      {word: 'remind', meaning: '기억나게 하다, 상기시키다'},
      {word: 'notice', meaning: '알아차리다, 눈치채다'},
      {word: 'ignore', meaning: '모르는 척하다, 무시하다'},
      {word: 'admit', meaning: '인정하다, 시인하다'},
      {word: 'spill', meaning: '(액체를) 쏟다, (비밀을) 털어놓다'},
      {word: 'overhear', meaning: '우연히 엿듣다'},
      {word: 'rush', meaning: '서두르다, 급하게 가다'},
      {word: 'struggle', meaning: '힘겹게 나아가다, 애를 먹다'},
      {word: 'prefer', meaning: '~을 더 좋아하다, 선호하다'},
      {word: 'guarantee', meaning: '보장하다, 장담하다'},
    ]
  },
  {
    id: 'tos_daily_master_1000_part1',
    emoji: '📚',
    title: '토스 & 일상 마스터 1000 (Part 1)',
    sub: '토익스피킹 기출 + 현지 일상 회화 필수 어휘 (1~120)',
    priority: '1000필수',
    pClass: 'p1',
    type: 'word',
    words: [
      /* Part 2 사진 묘사 동작 & 자세 (1~30) */
      {word: 'stroll', meaning: '한가롭게 거닐다, 산책하다'},
      {word: 'browse', meaning: '(상품 등을) 둘러보다, 훑어보다'},
      {word: 'lean against', meaning: '~에 기대다'},
      {word: 'reach for', meaning: '(물건을 잡으려고) 손을 뻗다'},
      {word: 'stack', meaning: '차곡차곡 쌓다, 포개다'},
      {word: 'display', meaning: '진열하다, 전시하다'},
      {word: 'occupy', meaning: '(자리나 공간을) 차지하다'},
      {word: 'board', meaning: '(비행기·기차 등에) 탑승하다'},
      {word: 'inspect', meaning: '자세히 살펴보다, 점검하다'},
      {word: 'distribute', meaning: '나누어 주다, 배포하다'},
      {word: 'applaud', meaning: '박수를 치다'},
      {word: 'gather', meaning: '모이다, 모으다'},
      {word: 'kneel', meaning: '무릎을 꿇다'},
      {word: 'crouch', meaning: '쪼그려 앉다'},
      {word: 'glance', meaning: '흘긋 보다'},
      {word: 'gaze', meaning: '응시하다, 바라보다'},
      {word: 'point at', meaning: '~을 손가락으로 가리키다'},
      {word: 'hold on to', meaning: '~을 꽉 잡다, 붙잡다'},
      {word: 'lift', meaning: '들어 올리다'},
      {word: 'carry', meaning: '나르다, 들고 가다'},
      {word: 'wipe', meaning: '(걸레 등으로) 닦다'},
      {word: 'scrub', meaning: '문질러 씻다'},
      {word: 'sweep', meaning: '(비로) 쓸다'},
      {word: 'pack', meaning: '짐을 싸다, 포장하다'},
      {word: 'unpack', meaning: '짐을 풀다'},
      {word: 'load', meaning: '(짐을) 싣다'},
      {word: 'unload', meaning: '(짐을) 내리다'},
      {word: 'fasten', meaning: '(안전벨트나 단추를) 매다, 채우다'},
      {word: 'adjust', meaning: '(위치나 옷매무새를) 맞추다, 조절하다'},
      {word: 'operate', meaning: '(기계 등을) 작동하다, 조작하다'},

      /* Part 2 주변 환경, 사물 & 거리 배경 (31~60) */
      {word: 'pavement', meaning: '포장도로, 보도'},
      {word: 'intersection', meaning: '교차로, 사거리'},
      {word: 'pedestrian', meaning: '보행자'},
      {word: 'countertop', meaning: '(가게·주방의) 조리대, 작업대'},
      {word: 'railing', meaning: '난간, 안전 손잡이'},
      {word: 'awning', meaning: '(가게 차양) 천막'},
      {word: 'overgrown', meaning: '무성한'},
      {word: 'scaffolding', meaning: '(공사장) 비계, 가설물'},
      {word: 'lamppost', meaning: '가로등 기둥'},
      {word: 'crosswalk', meaning: '횡단보도'},
      {word: 'curb', meaning: '도로 경계석, 차도와 인도 사이 턱'},
      {word: 'curtain', meaning: '커튼'},
      {word: 'bookshelf', meaning: '책장'},
      {word: 'trash can', meaning: '쓰레기통'},
      {word: 'vendor', meaning: '노점상, 판매인'},
      {word: 'stall', meaning: '(시장 등의) 가판대'},
      {word: 'fountain', meaning: '분수대'},
      {word: 'scenery', meaning: '풍경, 경치'},
      {word: 'statue', meaning: '조각상, 동상'},
      {word: 'lawn', meaning: '잔디밭'},
      {word: 'patio', meaning: '테라스, 베란다 공간'},
      {word: 'pathway', meaning: '오솔길, 보행로'},
      {word: 'shelter', meaning: '(비바람 등을 피하는) 쉼터'},
      {word: 'signpost', meaning: '이정표, 표지판'},
      {word: 'billboard', meaning: '광고판'},
      {word: 'escalator', meaning: '에스컬레이터'},
      {word: 'staircase', meaning: '계단'},
      {word: 'corridor', meaning: '복도'},
      {word: 'warehouse', meaning: '창고'},
      {word: 'dock', meaning: '부두, 선착장'},

      /* Part 3 & 일상 회화 빈출 취미/소비/외식 (61~90) */
      {word: 'frequently', meaning: '자주, 빈번하게'},
      {word: 'affordable', meaning: '가격이 알맞은, 감당할 수 있는'},
      {word: 'convenient', meaning: '편리한, 다루기 쉬운'},
      {word: 'atmosphere', meaning: '(장소의) 분위기'},
      {word: 'reasonable', meaning: '(가격 등이) 타당한, 적당한'},
      {word: 'preference', meaning: '선호, 더 좋아하는 것'},
      {word: 'relieve', meaning: '(스트레스나 피로를) 덜다, 완화하다'},
      {word: 'ingredient', meaning: '(요리의) 식재료, 성분'},
      {word: 'recommendation', meaning: '추천'},
      {word: 'commute', meaning: '통근하다, 출퇴근길'},
      {word: 'nearby', meaning: '인근의, 가까운'},
      {word: 'facility', meaning: '시설, 편의 시설'},
      {word: 'membership', meaning: '회원 자격, 회원권'},
      {word: 'recharge', meaning: '(휴식을 통해) 재충전하다'},
      {word: 'accessible', meaning: '접근하기 쉬운, 이용이 편리한'},
      {word: 'entertaining', meaning: '재미있는, 유쾌한'},
      {word: 'routine', meaning: '판에 박힌 일상, 루틴'},
      {word: 'discount', meaning: '할인'},
      {word: 'durable', meaning: '내구성이 좋은, 튼튼한'},
      {word: 'versatile', meaning: '다용도의, 다재다능한'},
      {word: 'beverage', meaning: '음료'},
      {word: 'dessert', meaning: '후식, 디저트'},
      {word: 'receipt', meaning: '영수증'},
      {word: 'refund', meaning: '환불'},
      {word: 'exchange', meaning: '교환하다'},
      {word: 'flavor', meaning: '풍미, 맛'},
      {word: 'portion', meaning: '(음식의) 1인분 양'},
      {word: 'appetizer', meaning: '식전 음식, 애피타이저'},
      {word: 'specialty', meaning: '특산물, 전문 요리'},
      {word: 'delivery', meaning: '배달, 배송'},

      /* Part 4 일정/공지/행사 핵심 비즈니스 어휘 (91~120) */
      {word: 'postpone', meaning: '연기하다, 미루다'},
      {word: 'reschedule', meaning: '일정을 변경하다'},
      {word: 'cancel', meaning: '취소하다'},
      {word: 'conduct', meaning: '(행사·조사 등을) 진행하다, 수행하다'},
      {word: 'keynote', meaning: '(기조가 되는) 기조연설'},
      {word: 'registration', meaning: '등록, 참가 신청'},
      {word: 'participant', meaning: '참가자'},
      {word: 'fee', meaning: '수수료, 참가비'},
      {word: 'session', meaning: '(회의·수업 등의) 세션, 시간'},
      {word: 'banquet', meaning: '연회, 만찬'},
      {word: 'annual', meaning: '매년의, 연례의'},
      {word: 'applicant', meaning: '지원자'},
      {word: 'qualification', meaning: '지원 자격, 자격 요건'},
      {word: 'fluent', meaning: '유창한, 능숙한'},
      {word: 'itinerary', meaning: '출장/여행 일정표'},
      {word: 'certificate', meaning: '자격증, 증명서'},
      {word: 'director', meaning: '이사, 부서 책임자'},
      {word: 'relocate', meaning: '(사무실·거주지를) 이전하다'},
      {word: 'available', meaning: '시간이 비어 있는, 이용 가능한'},
      {word: 'confirm', meaning: '확인하다, 확정짓다'},
      {word: 'attend', meaning: '참석하다'},
      {word: 'absence', meaning: '결석, 부재'},
      {word: 'agenda', meaning: '의제, 안건'},
      {word: 'presentation', meaning: '발표, 프레젠테이션'},
      {word: 'seminar', meaning: '세미나, 강습회'},
      {word: 'workshop', meaning: '워크숍, 연수'},
      {word: 'briefing', meaning: '간략한 보고, 브리핑'},
      {word: 'deadline', meaning: '마감일, 제출 기한'},
      {word: 'venue', meaning: '(행사 등이 열리는) 장소'},
      {word: 'host', meaning: '주최하다, 진행자'}
    ]
  },
  {
    id: 'tos_daily_master_1000_part2',
    emoji: '💡',
    title: '토스 & 일상 마스터 1000 (Part 2)',
    sub: 'Part 5 논리/의견 어휘 + 일상 필수 감정·상태 (121~240)',
    priority: '1000필수',
    pClass: 'p2b',
    type: 'word',
    words: [
      /* Part 5 업무 효율 & 직장 생활 논리 (121~150) */
      {word: 'productive', meaning: '생산적인'},
      {word: 'efficient', meaning: '효율적인'},
      {word: 'collaborate', meaning: '협력하다, 공동 작업하다'},
      {word: 'distract', meaning: '(집중을) 방해하다, 산만하게 하다'},
      {word: 'flexible', meaning: '유연한, 탄력적인 (근무제 등)'},
      {word: 'broaden', meaning: '(시야·견문을) 넓히다'},
      {word: 'perspective', meaning: '관점, 시각, 견문'},
      {word: 'motivate', meaning: '동기를 부여하다'},
      {word: 'morale', meaning: '(팀·직원의) 사기, 의욕'},
      {word: 'feedback', meaning: '피드백, 의견 수렴'},
      {word: 'reputation', meaning: '평판, 명성'},
      {word: 'priority', meaning: '우선순위'},
      {word: 'workload', meaning: '업무량'},
      {word: 'achievement', meaning: '성취, 달성한 성과'},
      {word: 'incentive', meaning: '보상책, 인센티브'},
      {word: 'cooperation', meaning: '협력, 협조'},
      {word: 'resolve', meaning: '(문제·갈등을) 해결하다'},
      {word: 'satisfaction', meaning: '만족도'},
      {word: 'overtime', meaning: '초과 근무, 야근'},
      {word: 'performance', meaning: '업무 실적, 성과'},
      {word: 'competence', meaning: '능력, 역량'},
      {word: 'leadership', meaning: '통솔력, 리더십'},
      {word: 'initiative', meaning: '솔선수범, 주도권'},
      {word: 'contribution', meaning: '기여, 공헌'},
      {word: 'supervise', meaning: '감독하다, 지도하다'},
      {word: 'delegate', meaning: '(권한·업무를) 위임하다, 맡기다'},
      {word: 'streamline', meaning: '(업무 등을) 간소화하다, 능률화하다'},
      {word: 'multitask', meaning: '다중 작업을 하다'},
      {word: 'punctual', meaning: '시간을 잘 지키는'},
      {word: 'absenteeism', meaning: '잦은 결근, 무단결석'},

      /* Part 5 고객 응대, 비즈니스 & 사회 이슈 (151~180) */
      {word: 'inconvenience', meaning: '불편, 수고'},
      {word: 'apologize', meaning: '사과하다'},
      {word: 'compensation', meaning: '보상, 배상'},
      {word: 'alternative', meaning: '대안, 대체 가능한 것'},
      {word: 'malfunction', meaning: '(기계의) 오작동, 고장'},
      {word: 'shortage', meaning: '부족, 결핍'},
      {word: 'urgent', meaning: '긴급한, 촉박한'},
      {word: 'reliable', meaning: '믿을 만한, 신뢰할 수 있는'},
      {word: 'inaccurate', meaning: '부정확한, 오류가 있는'},
      {word: 'loyal', meaning: '충성스러운 (단골 고객 등)'},
      {word: 'attract', meaning: '(고객·관심을) 끌다, 유치하다'},
      {word: 'investment', meaning: '투자'},
      {word: 'profitable', meaning: '수익성이 높은, 이익이 되는'},
      {word: 'pollute', meaning: '오염시키다'},
      {word: 'protect', meaning: '보호하다, 지키다'},
      {word: 'conserve', meaning: '(자원 등을) 아끼다, 보존하다'},
      {word: 'disposable', meaning: '일회용의'},
      {word: 'renewable', meaning: '재생 가능한 (에너지 등)'},
      {word: 'competitive', meaning: '경쟁력 있는, 치열한'},
      {word: 'strategy', meaning: '전략, 방안'},
      {word: 'implement', meaning: '(정책 등을) 실행하다, 도입하다'},
      {word: 'guarantee', meaning: '보증하다, 장담하다'},
      {word: 'maintenance', meaning: '유지 보수, 정기 점검'},
      {word: 'defect', meaning: '결함, 하자'},
      {word: 'complaint', meaning: '불만, 항의'},
      {word: 'survey', meaning: '설문조사'},
      {word: 'trend', meaning: '동향, 추세'},
      {word: 'budget', meaning: '예산'},
      {word: 'deficit', meaning: '적자, 부족액'},
      {word: 'expand', meaning: '(사업·인맥 등을) 확장하다'},

      /* 현지 일상 필수 감정 & 기분 묘사 (181~210) */
      {word: 'exhausted', meaning: '기진맥진한, 녹초가 된'},
      {word: 'drained', meaning: '진이 다 빠진, 기운 없는'},
      {word: 'frustrated', meaning: '답답한, 뜻대로 안 돼 짜증 나는'},
      {word: 'awkward', meaning: '어색한, 민망한'},
      {word: 'relieved', meaning: '안도하는, 마음이 놓이는'},
      {word: 'hectic', meaning: '눈코 뜰 새 없이 바쁜, 정신없는'},
      {word: 'clueless', meaning: '전혀 감을 못 잡는, 아예 모르는'},
      {word: 'decent', meaning: '꽤 괜찮은, 그럭저럭 좋은'},
      {word: 'messy', meaning: '지저분한, 어질러진'},
      {word: 'spotless', meaning: '먼지 하나 없이 아주 깨끗한'},
      {word: 'picky', meaning: '입맛이나 성격이 까다로운'},
      {word: 'generous', meaning: '인심 좋은, 너그러운'},
      {word: 'spontaneous', meaning: '즉흥적인, 사전 계획 없는'},
      {word: 'skeptical', meaning: '회의적인, 반신반의하는'},
      {word: 'clumsy', meaning: '칠칠치 못한, 덜렁대는'},
      {word: 'hilarious', meaning: '배꼽 잡게 웃긴, 대단히 재미있는'},
      {word: 'stuffy', meaning: '(방 공기 등이) 답답하고 탁한'},
      {word: 'cozy', meaning: '아늑하고 편안한'},
      {word: 'overwhelming', meaning: '벅찬, 압도적인'},
      {word: 'craving', meaning: '(음식 등이) 몹시 땡김, 갈망'},
      {word: 'annoyed', meaning: '짜증이 난'},
      {word: 'grumpy', meaning: '심술궂은, 툴툴거리는'},
      {word: 'furious', meaning: '격노한, 몹시 화가 난'},
      {word: 'terrified', meaning: '겁에 질린, 무서워하는'},
      {word: 'nervous', meaning: '긴장한, 떨리는'},
      {word: 'gloomy', meaning: '우울한, 침울한'},
      {word: 'delighted', meaning: '아주 기뻐하는'},
      {word: 'thrilled', meaning: '짜릿한, 너무나 신난'},
      {word: 'calm', meaning: '침착한, 차분한'},
      {word: 'chill', meaning: '느긋한, 쿨한'},

      /* 성격 & 대인관계 필수 어휘 (211~240) */
      {word: 'outgoing', meaning: '외향적인, 활발한'},
      {word: 'introverted', meaning: '내향적인, 소심한'},
      {word: 'stubborn', meaning: '고집이 센, 완강한'},
      {word: 'humble', meaning: '겸손한'},
      {word: 'arrogant', meaning: '거만한, 건방진'},
      {word: 'reliable', meaning: '믿음직한, 의지할 수 있는'},
      {word: 'considerate', meaning: '사려 깊은, 배려심 있는'},
      {word: 'selfish', meaning: '이기적인'},
      {word: 'easygoing', meaning: '성격이 둥글둥글한, 털털한'},
      {word: 'sensitive', meaning: '예민한, 감수성이 풍부한'},
      {word: 'curious', meaning: '호기심 많은, 궁금해하는'},
      {word: 'impatient', meaning: '참을성 없는, 조급한'},
      {word: 'polite', meaning: '예의 바른, 정중한'},
      {word: 'rude', meaning: '무례한, 버릇없는'},
      {word: 'honest', meaning: '정직한, 솔직한'},
      {word: 'deceitful', meaning: '기만적인, 남을 속이는'},
      {word: 'enthusiastic', meaning: '열정적인, 열의를 보이는'},
      {word: 'supportive', meaning: '힘을 주는, 응원하는'},
      {word: 'bossy', meaning: '이래라저래라 하는'},
      {word: 'sincere', meaning: '진실된, 진심 어린'},
      {word: 'laid-back', meaning: '느긋하고 편안한'},
      {word: 'cautious', meaning: '신중한, 조심성 있는'},
      {word: 'affectionate', meaning: '다정한, 애정 어린'},
      {word: 'competitive', meaning: '승부욕이 강한'},
      {word: 'optimistic', meaning: '낙천적인, 긍정적인'},
      {word: 'pessimistic', meaning: '비관적인, 부정적인'},
      {word: 'loyal', meaning: '의리 있는, 충성스러운'},
      {word: 'open-minded', meaning: '열린 사고를 가진, 개방적인'},
      {word: 'narrow-minded', meaning: '편협한, 속 좁은'},
      {word: 'cooperative', meaning: '협조적인'}
    ]
  },
  {
    id: 'tos_daily_master_1000_part3',
    emoji: '🏃',
    title: '토스 & 일상 마스터 1000 (Part 3)',
    sub: '일상 동작·생활 루틴 + 교통·여행·여가 어휘 (241~360)',
    priority: '1000필수',
    pClass: 'p3b',
    type: 'word',
    words: [
      /* 현지 일상 필수 소통 & 행동 동사 (241~270) */
      {word: 'interrupt', meaning: '말을 끊다, 방해하다'},
      {word: 'procrastinate', meaning: '할 일을 미루다, 늑장 부리다'},
      {word: 'distract', meaning: '주의를 딴 데로 돌리다, 산만하게 하다'},
      {word: 'tolerate', meaning: '참다, 견디다'},
      {word: 'convince', meaning: '설득하다, 납득시키다'},
      {word: 'assume', meaning: '추정하다, 당연히 그럴 거라 생각하다'},
      {word: 'hesitate', meaning: '망설이다, 주저하다'},
      {word: 'complain', meaning: '불평하다, 투덜거리다'},
      {word: 'catch up', meaning: '밀린 이야기나 일을 따라잡다'},
      {word: 'remind', meaning: '기억나게 하다, 상기시키다'},
      {word: 'notice', meaning: '알아차리다, 눈치채다'},
      {word: 'ignore', meaning: '모르는 척하다, 무시하다'},
      {word: 'admit', meaning: '인정하다, 시인하다'},
      {word: 'spill', meaning: '(액체를) 쏟다, (비밀을) 털어놓다'},
      {word: 'overhear', meaning: '우연히 엿듣다'},
      {word: 'rush', meaning: '서두르다, 급하게 가다'},
      {word: 'struggle', meaning: '힘겹게 나아가다, 애를 먹다'},
      {word: 'prefer', meaning: '~을 더 좋아하다, 선호하다'},
      {word: 'persuade', meaning: '설득하여 ~하게 하다'},
      {word: 'confess', meaning: '자백하다, 고백하다'},
      {word: 'blame', meaning: '탓하다, 비난하다'},
      {word: 'forgive', meaning: '용서하다'},
      {word: 'warn', meaning: '경고하다, 주의를 주다'},
      {word: 'tease', meaning: '놀리다, 장난치다'},
      {word: 'brag', meaning: '자랑하다, 으스대다'},
      {word: 'whisper', meaning: '속삭이다, 귓속말하다'},
      {word: 'yell', meaning: '소리치다, 고함지르다'},
      {word: 'nod', meaning: '고개를 끄덕이다'},
      {word: 'shrug', meaning: '어깨를 으쓱하다'},
      {word: 'sigh', meaning: '한숨을 쉬다'},

      /* 집안일, 주거 & 생활 루틴 (271~300) */
      {word: 'laundry', meaning: '세탁물, 빨래'},
      {word: 'detergent', meaning: '세탁 세제'},
      {word: 'chore', meaning: '집안일, 허드렛일'},
      {word: 'appliance', meaning: '가전제품'},
      {word: 'renovate', meaning: '개조하다, 보수하다'},
      {word: 'decorate', meaning: '장식하다, 꾸미다'},
      {word: 'tidy', meaning: '정리하다, 깔끔한'},
      {word: 'clutter', meaning: '어수선함, 잡동사니'},
      {word: 'garbage', meaning: '쓰레기'},
      {word: 'leftovers', meaning: '남은 음식'},
      {word: 'utility', meaning: '공공요금 (전기·가스·수도)'},
      {word: 'commute', meaning: '통근하다, 통학하다'},
      {word: 'errand', meaning: '심부름, 볼일'},
      {word: 'subscription', meaning: '정기 구독'},
      {word: 'pantry', meaning: '식료품 저장실'},
      {word: 'refrigerator', meaning: '냉장고'},
      {word: 'dishwasher', meaning: '식기세척기'},
      {word: 'vacuum', meaning: '진공청소기, 청소기를 돌리다'},
      {word: 'drain', meaning: '배수구, 물을 빼다'},
      {word: 'leak', meaning: '새다, 누수'},
      {word: 'plumber', meaning: '배관공'},
      {word: 'landlord', meaning: '집주인, 임대인'},
      {word: 'tenant', meaning: '세입자'},
      {word: 'rent', meaning: '월세, 임대료'},
      {word: 'deposit', meaning: '보증금, 예금'},
      {word: 'neighborhood', meaning: '동네, 이웃'},
      {word: 'balcony', meaning: '발코니, 베란다'},
      {word: 'garage', meaning: '차고'},
      {word: 'furnish', meaning: '(가구를) 비치하다'},
      {word: 'maintain', meaning: '유지하다, 관리하다'},

      /* 교통, 이동 & 여행 어휘 (301~330) */
      {word: 'fare', meaning: '(교통) 요금'},
      {word: 'transfer', meaning: '환승하다, 갈아타다'},
      {word: 'route', meaning: '노선, 경로'},
      {word: 'congestion', meaning: '(교통) 혼잡, 정체'},
      {word: 'rush hour', meaning: '출퇴근 혼잡 시간대'},
      {word: 'delay', meaning: '지연, 연착'},
      {word: 'departure', meaning: '출발'},
      {word: 'arrival', meaning: '도착'},
      {word: 'destination', meaning: '목적지'},
      {word: 'luggage', meaning: '수하물, 짐'},
      {word: 'boarding pass', meaning: '탑승권'},
      {word: 'customs', meaning: '세관, 세관 검사소'},
      {word: 'accommodation', meaning: '숙박 시설'},
      {word: 'souvenir', meaning: '기념품'},
      {word: 'sightseeing', meaning: '관광'},
      {word: 'guided tour', meaning: '가이드 딸린 투어'},
      {word: 'landmark', meaning: '명소, 주요 건조물'},
      {word: 'terminal', meaning: '터미널, 종점'},
      {word: 'shuttle', meaning: '정기 왕복 버스/차량'},
      {word: 'subway line', meaning: '지하철 노선'},
      {word: 'carpool', meaning: '카풀을 하다'},
      {word: 'detour', meaning: '우회로, 둘러가는 길'},
      {word: 'highway', meaning: '고속도로'},
      {word: 'toll', meaning: '도로 통행료'},
      {word: 'reservation', meaning: '예약'},
      {word: 'overbook', meaning: '예약을 정원 이상 받다'},
      {word: 'complimentary', meaning: '무료의 (호텔 서비스 등)'},
      {word: 'currency', meaning: '통화, 화폐'},
      {word: 'exchange rate', meaning: '환율'},
      {word: 'jet lag', meaning: '시차로 인한 피로'},

      /* 디지털, 스마트폰 & 소셜 미디어 (331~360) */
      {word: 'notification', meaning: '알림'},
      {word: 'update', meaning: '업데이트하다, 최신 정보'},
      {word: 'install', meaning: '설치하다'},
      {word: 'uninstall', meaning: '삭제하다'},
      {word: 'browse', meaning: '(웹사이트를) 검색하다, 둘러보다'},
      {word: 'upload', meaning: '업로드하다, 올리다'},
      {word: 'download', meaning: '다운로드하다'},
      {word: 'post', meaning: '게시물, 게시하다'},
      {word: 'comment', meaning: '댓글, 의견을 남기다'},
      {word: 'share', meaning: '공유하다'},
      {word: 'scroll', meaning: '화면을 스크롤하다'},
      {word: 'swipe', meaning: '화면을 슥 넘기다'},
      {word: 'charge', meaning: '(배터리를) 충전하다'},
      {word: 'low battery', meaning: '배터리 부족'},
      {word: 'charger', meaning: '충전기'},
      {word: 'wireless', meaning: '무선의'},
      {word: 'connection', meaning: '연결 상태, 접속'},
      {word: 'reboot', meaning: '재부팅하다'},
      {word: 'crash', meaning: '(프로그램·앱이) 튕기다, 다운되다'},
      {word: 'freeze', meaning: '(화면이) 멈추다, 렉 걸리다'},
      {word: 'glitch', meaning: '작은 시스템 오류, 결함'},
      {word: 'privacy', meaning: '개인정보, 사생활'},
      {word: 'settings', meaning: '환경설정'},
      {word: 'profile', meaning: '프로필'},
      {word: 'tag', meaning: '(사진 등에) 태그를 달다'},
      {word: 'follow', meaning: '팔로우하다, 구독하다'},
      {word: 'unfollow', meaning: '팔로우를 취소하다'},
      {word: 'block', meaning: '차단하다'},
      {word: 'mute', meaning: '알림을 무음으로 하다'},
      {word: 'backup', meaning: '백업하다, 예비 파일'}
    ]
  },
  {
    id: 'tos_daily_master_1000_part4',
    emoji: '💼',
    title: '토스 & 일상 마스터 1000 (Part 4)',
    sub: '인사·직무·재무 핵심 어휘 + 쇼핑·소비 (361~480)',
    priority: '1000필수',
    pClass: 'p4b',
    type: 'word',
    words: [
      /* 인사, 채용 & 구직 (361~390) */
      {word: 'recruit', meaning: '채용하다, 모집하다'},
      {word: 'candidate', meaning: '후보자, 지원자'},
      {word: 'resume', meaning: '이력서'},
      {word: 'cover letter', meaning: '자기소개서'},
      {word: 'reference', meaning: '추천인, 추천서'},
      {word: 'hire', meaning: '고용하다'},
      {word: 'fire', meaning: '해고하다'},
      {word: 'lay off', meaning: '(불경기로 인해) 해고하다'},
      {word: 'resign', meaning: '사임하다, 사직하다'},
      {word: 'retire', meaning: '은퇴하다'},
      {word: 'promote', meaning: '승진시키다, 홍보하다'},
      {word: 'demote', meaning: '강등시키다'},
      {word: 'transfer', meaning: '전근/전보를 보내다'},
      {word: 'shift', meaning: '교대 근무조, 근무 시간'},
      {word: 'payroll', meaning: '급여 대장, 급여 총액'},
      {word: 'wage', meaning: '(주로 시급제) 임금'},
      {word: 'salary', meaning: '(연봉/월급제) 급여'},
      {word: 'benefit', meaning: '복리후생, 혜택'},
      {word: 'allowance', meaning: '수당, 용돈'},
      {word: 'leave', meaning: '휴가 (sick leave, annual leave)'},
      {word: 'orientation', meaning: '신입 사원 교육, 오리엔테이션'},
      {word: 'probation', meaning: '수습 기간'},
      {word: 'vacancy', meaning: '결원, 공석'},
      {word: 'evaluate', meaning: '평가하다'},
      {word: 'appraisal', meaning: '(인사) 고과, 평가'},
      {word: 'turnover', meaning: '이직률, 매출액'},
      {word: 'pension', meaning: '연금'},
      {word: 'union', meaning: '노동조합'},
      {word: 'expertise', meaning: '전문 지식, 전문성'},
      {word: 'credential', meaning: '자격, 자격 증명'},

      /* 직무 능력, 평가 & 성과 (391~420) */
      {word: 'capable', meaning: '능력 있는, 유능한'},
      {word: 'innovative', meaning: '혁신적인'},
      {word: 'creativity', meaning: '창의성'},
      {word: 'problem-solving', meaning: '문제 해결 (능력)'},
      {word: 'adaptable', meaning: '적응력 있는, 융통성 있는'},
      {word: 'diligent', meaning: '성실한, 부지런한'},
      {word: 'proactive', meaning: '주도적인, 예방 차원의'},
      {word: 'responsible', meaning: '책임감 있는'},
      {word: 'dependable', meaning: '의지할 수 있는, 신뢰할 수 있는'},
      {word: 'observant', meaning: '관찰력 있는, 눈썰미 좋은'},
      {word: 'meticulous', meaning: '꼼꼼한, 세심한'},
      {word: 'ambitious', meaning: '야심 찬, 열정적인'},
      {word: 'persistent', meaning: '끈기 있는, 집요한'},
      {word: 'dedication', meaning: '헌신, 전념'},
      {word: 'commitment', meaning: '약속, 헌신'},
      {word: 'accomplishment', meaning: '업적, 성취'},
      {word: 'milestone', meaning: '중요한 단계, 획기적인 사건'},
      {word: 'target', meaning: '목표, 표적'},
      {word: 'objective', meaning: '목적, 객관적인'},
      {word: 'exceed', meaning: '(한도·예상을) 초과하다, 뛰어넘다'},
      {word: 'assess', meaning: '평가하다, 사정하다'},
      {word: 'criterion', meaning: '기준, 척도 (복수: criteria)'},
      {word: 'flaw', meaning: '결함, 흠'},
      {word: 'shortcoming', meaning: '단점, 결점'},
      {word: 'strength', meaning: '강점, 장점'},
      {word: 'weakness', meaning: '약점'},
      {word: 'potential', meaning: '잠재력, 가능성'},
      {word: 'constructive', meaning: '건설적인 (피드백 등)'},
      {word: 'mentorship', meaning: '멘토링, 지도'},
      {word: 'recognition', meaning: '인정, 포상'},

      /* 재무, 예산 & 계약 (421~450) */
      {word: 'budget', meaning: '예산'},
      {word: 'estimate', meaning: '견적서, 추정하다'},
      {word: 'quote', meaning: '견적(액), 인용하다'},
      {word: 'invoice', meaning: '송장, 청구서'},
      {word: 'revenue', meaning: '수익, 매출'},
      {word: 'expense', meaning: '비용, 지출'},
      {word: 'profit', meaning: '이익, 이윤'},
      {word: 'loss', meaning: '손실, 적자'},
      {word: 'margin', meaning: '이윤 폭, 마진'},
      {word: 'fund', meaning: '자금, 기금'},
      {word: 'sponsor', meaning: '후원하다, 스폰서'},
      {word: 'audit', meaning: '회계 감사'},
      {word: 'invest', meaning: '투자하다'},
      {word: 'shareholder', meaning: '주주'},
      {word: 'asset', meaning: '자산, 재산'},
      {word: 'liability', meaning: '부채, 책임'},
      {word: 'bankrupt', meaning: '파산한'},
      {word: 'transaction', meaning: '거래'},
      {word: 'balance', meaning: '잔액, 잔고'},
      {word: 'transfer', meaning: '이체하다, 송금하다'},
      {word: 'negotiate', meaning: '협상하다'},
      {word: 'contract', meaning: '계약, 계약서'},
      {word: 'agreement', meaning: '합의, 협정'},
      {word: 'term', meaning: '조건, 조항, 기간'},
      {word: 'condition', meaning: '상태, 조건'},
      {word: 'sign', meaning: '서명하다'},
      {word: 'authorize', meaning: '인가하다, 권한을 부여하다'},
      {word: 'valid', meaning: '유효한, 타당한'},
      {word: 'expire', meaning: '만료되다'},
      {word: 'renew', meaning: '갱신하다'},

      /* 쇼핑, 상거래 & 소비 일상 (451~480) */
      {word: 'retail', meaning: '소매 (retail price: 소매가)'},
      {word: 'wholesale', meaning: '도매'},
      {word: 'inventory', meaning: '재고, 재고 목록'},
      {word: 'stock', meaning: '재고품 (out of stock: 품절된)'},
      {word: 'merchandise', meaning: '상품, 제품'},
      {word: 'catalog', meaning: '상품 안내서, 카탈로그'},
      {word: 'display', meaning: '진열하다'},
      {word: 'aisle', meaning: '(마트·비행기 등의) 통로'},
      {word: 'cashier', meaning: '계산원'},
      {word: 'checkout', meaning: '계산대, 체크아웃'},
      {word: 'receipt', meaning: '영수증'},
      {word: 'refund', meaning: '환불, 환불하다'},
      {word: 'exchange', meaning: '교환, 교환하다'},
      {word: 'warranty', meaning: '품질 보증(서)'},
      {word: 'guarantee', meaning: '보장하다, 장담하다'},
      {word: 'discount', meaning: '할인'},
      {word: 'clearance', meaning: '재고 정리 (세일)'},
      {word: 'voucher', meaning: '상품권, 쿠폰'},
      {word: 'affordable', meaning: '가격이 알맞은, 저렴한'},
      {word: 'pricey', meaning: '값비싼 (expensive의 구어체)'},
      {word: 'rip-off', meaning: '바가지 (That\'s a rip-off!)'},
      {word: 'bargain', meaning: '싸게 산 물건, 흥정하다'},
      {word: 'purchase', meaning: '구매하다, 구매품'},
      {word: 'shipping', meaning: '배송, 운송'},
      {word: 'delivery', meaning: '배달'},
      {word: 'track', meaning: '추적하다 (배송 조회)'},
      {word: 'defect', meaning: '결함, 하자'},
      {word: 'flawless', meaning: '흠집 없는, 완벽한'},
      {word: 'counterfeit', meaning: '위조의, 가품 (짝퉁)'},
      {word: 'authentic', meaning: '진품의, 진짜의'}
    ]
  },
  {
    id: 'tos_daily_master_1000_part5',
    emoji: '🌱',
    title: '토스 & 일상 마스터 1000 (Part 5)',
    sub: '환경·기술 + 외식·건강 필수 어휘 (481~600)',
    priority: '1000필수',
    pClass: 'p5b',
    type: 'word',
    words: [
      /* 환경, 에너지 & 지속가능성 (481~510) */
      {word: 'pollution', meaning: '오염, 공해'},
      {word: 'emission', meaning: '배출, 배출물 (탄소 배출 등)'},
      {word: 'conserve', meaning: '(자원·에너지를) 아끼다, 보존하다'},
      {word: 'preserve', meaning: '(자연·유적을) 지키다, 보존하다'},
      {word: 'recycle', meaning: '재활용하다'},
      {word: 'reuse', meaning: '재사용하다'},
      {word: 'disposable', meaning: '일회용의'},
      {word: 'biodegradable', meaning: '자연 분해되는, 생분해성의'},
      {word: 'renewable', meaning: '재생 가능한 (태양광 등)'},
      {word: 'solar energy', meaning: '태양 에너지'},
      {word: 'carbon footprint', meaning: '탄소 발자국 (배출량)'},
      {word: 'global warming', meaning: '지구 온난화'},
      {word: 'climate change', meaning: '기후 변화'},
      {word: 'ecosystem', meaning: '생태계'},
      {word: 'habitat', meaning: '(동식물의) 서식지'},
      {word: 'endangered', meaning: '멸종 위기에 처한'},
      {word: 'extinct', meaning: '멸종된'},
      {word: 'landfill', meaning: '쓰레기 매립지'},
      {word: 'contamination', meaning: '오염 (물·토양 등)'},
      {word: 'purify', meaning: '정화하다, 깨끗이 하다'},
      {word: 'sustainable', meaning: '지속 가능한'},
      {word: 'eco-friendly', meaning: '친환경적인'},
      {word: 'deplete', meaning: '(자원을) 고갈시키다'},
      {word: 'exhaust', meaning: '배기가스, 고갈시키다'},
      {word: 'regulation', meaning: '규제, 단속'},
      {word: 'violate', meaning: '(법·규칙을) 위반하다'},
      {word: 'fine', meaning: '벌금, 과태료'},
      {word: 'impose', meaning: '(세금·벌금을) 부과하다'},
      {word: 'ban', meaning: '금지하다, 금지령'},
      {word: 'awareness', meaning: '(환경 등에 대한) 인식, 의식'},

      /* 기술, IT & 업무 자동화 (511~540) */
      {word: 'automation', meaning: '자동화'},
      {word: 'artificial intelligence', meaning: '인공지능 (AI)'},
      {word: 'algorithm', meaning: '알고리즘'},
      {word: 'database', meaning: '데이터베이스'},
      {word: 'cloud storage', meaning: '클라우드 저장소'},
      {word: 'cybersecurity', meaning: '사이버 보안'},
      {word: 'encryption', meaning: '암호화'},
      {word: 'hacker', meaning: '해커'},
      {word: 'malware', meaning: '악성 소프트웨어'},
      {word: 'interface', meaning: '사용자 인터페이스 (화면 UI)'},
      {word: 'user-friendly', meaning: '사용하기 쉬운, 직관적인'},
      {word: 'compatible', meaning: '(기기·프로그램이) 호환되는'},
      {word: 'upgrade', meaning: '업그레이드하다, 향상시키다'},
      {word: 'virtual', meaning: '가상의 (VR, 가상회의 등)'},
      {word: 'remote', meaning: '원격의 (remote work: 원격 근무)'},
      {word: 'wireless', meaning: '무선의'},
      {word: 'connectivity', meaning: '연결성, 접속 상태'},
      {word: 'bandwidth', meaning: '대역폭, 데이터 전송 용량'},
      {word: 'streamline', meaning: '(시스템을) 효율화하다, 간소화하다'},
      {word: 'innovate', meaning: '혁신하다'},
      {word: 'cutting-edge', meaning: '최첨단의'},
      {word: 'state-of-the-art', meaning: '최신식의, 최고 수준의'},
      {word: 'obsolete', meaning: '구식의, 더 이상 안 쓰이는'},
      {word: 'outdated', meaning: '시대에 뒤처진'},
      {word: 'glitch', meaning: '일시적인 시스템 오류'},
      {word: 'bug', meaning: '(소프트웨어) 오류, 버그'},
      {word: 'troubleshoot', meaning: '문제점을 찾아 해결하다'},
      {word: 'device', meaning: '기기, 장치'},
      {word: 'portable', meaning: '휴대용의'},
      {word: 'wearable', meaning: '웨어러블의, 착용형의'},

      /* 외식, 요리 & 맛/식감 묘사 (541~570) */
      {word: 'culinary', meaning: '요리의, 음식의'},
      {word: 'chef', meaning: '주방장, 요리사'},
      {word: 'recipe', meaning: '요리법, 조리법'},
      {word: 'ingredient', meaning: '식재료'},
      {word: 'savory', meaning: '풍미 있는, 짭조름하고 감칠맛 나는'},
      {word: 'sour', meaning: '신, 새콤한'},
      {word: 'bitter', meaning: '쓴, 쌉싸름한'},
      {word: 'greasy', meaning: '기름진, 느글거리는'},
      {word: 'bland', meaning: '(간이 안 되어) 싱거운, 밋밋한'},
      {word: 'spicy', meaning: '매운'},
      {word: 'mild', meaning: '순한, 자극적이지 않은'},
      {word: 'crispy', meaning: '바삭바삭한'},
      {word: 'crunchy', meaning: '오독오독 씹히는'},
      {word: 'chewy', meaning: '쫄깃쫄깃한, 질긴'},
      {word: 'tender', meaning: '(고기 등이) 부드러운, 연한'},
      {word: 'stale', meaning: '(빵·과자 등이) 눅눅한, 마른'},
      {word: 'fresh', meaning: '신선한, 갓 만든'},
      {word: 'mouth-watering', meaning: '군침이 도는'},
      {word: 'rich', meaning: '(맛이) 진한, 풍부한'},
      {word: 'appetizing', meaning: '식욕을 돋우는, 맛있어 보이는'},
      {word: 'portion', meaning: '(음식) 1인분 양'},
      {word: 'leftovers', meaning: '남은 음식'},
      {word: 'seasoning', meaning: '양념, 조미료'},
      {word: 'garnish', meaning: '(음식 위의) 고명, 장식'},
      {word: 'raw', meaning: '날것의, 익히지 않은'},
      {word: 'marinate', meaning: '(고기를) 양념에 재우다'},
      {word: 'roast', meaning: '(오븐·불에) 굽다'},
      {word: 'steam', meaning: '찌다, 증기로 익히다'},
      {word: 'boil', meaning: '끓이다, 삶다'},
      {word: 'stir-fry', meaning: '(기름에) 달달 볶다'},

      /* 건강, 질병 & 병원/의료 표현 (571~600) */
      {word: 'symptom', meaning: '증상'},
      {word: 'prescription', meaning: '처방전'},
      {word: 'prescribe', meaning: '처방하다'},
      {word: 'medication', meaning: '약물, 약'},
      {word: 'painkiller', meaning: '진통제'},
      {word: 'ointment', meaning: '연고'},
      {word: 'dose', meaning: '(약의) 1회 복용량'},
      {word: 'side effect', meaning: '부작용'},
      {word: 'allergy', meaning: '알레르기'},
      {word: 'fever', meaning: '열, 고열'},
      {word: 'dizzy', meaning: '어지러운'},
      {word: 'nauseous', meaning: '속이 울렁거리는, 메스꺼운'},
      {word: 'sore throat', meaning: '목 통증, 인후통'},
      {word: 'stuffy nose', meaning: '코막힘'},
      {word: 'runny nose', meaning: '콧물'},
      {word: 'cough', meaning: '기침하다, 기침'},
      {word: 'indigestion', meaning: '소화불량'},
      {word: 'sprain', meaning: '(발목 등을) 삐다, 염좌'},
      {word: 'fracture', meaning: '골절, 부러지다'},
      {word: 'bruise', meaning: '멍, 타박상'},
      {word: 'swollen', meaning: '부어오른'},
      {word: 'contagious', meaning: '전염성이 있는'},
      {word: 'immune system', meaning: '면역 체계'},
      {word: 'checkup', meaning: '건강 검진'},
      {word: 'clinic', meaning: '개인 병원, 의원'},
      {word: 'appointment', meaning: '(병원 등의) 진료 예약'},
      {word: 'recover', meaning: '회복하다, 완쾌되다'},
      {word: 'hygiene', meaning: '위생, 청결'},
      {word: 'dehydrated', meaning: '탈수 증세가 있는'},
      {word: 'fatigue', meaning: '극심한 피로'}
    ]
  },
  {
    id: 'tos_daily_master_1000_part6',
    emoji: '🎨',
    title: '토스 & 일상 마스터 1000 (Part 6)',
    sub: '문화·예술·마케팅 + 날씨·시간 표현 (601~720)',
    priority: '1000필수',
    pClass: 'p1',
    type: 'word',
    words: [
      /* 문화, 여가 & 엔터테인먼트 (601~630) */
      {word: 'exhibition', meaning: '전시회, 박람회'},
      {word: 'gallery', meaning: '미술관, 화랑'},
      {word: 'admission', meaning: '입장료, 입장'},
      {word: 'performance', meaning: '공연, 연주'},
      {word: 'spectator', meaning: '(경기·공연 등의) 관객, 관중'},
      {word: 'audience', meaning: '(강연·공연의) 청중, 관객'},
      {word: 'orchestra', meaning: '오케스트라, 관현악단'},
      {word: 'choir', meaning: '합창단, 성가대'},
      {word: 'rehearsal', meaning: '예행연습, 리허설'},
      {word: 'instrument', meaning: '악기, 도구'},
      {word: 'genre', meaning: '(음악·영화 등의) 장르'},
      {word: 'plot', meaning: '(소설·영화의) 줄거리'},
      {word: 'review', meaning: '후기, 서평, 비평'},
      {word: 'masterpiece', meaning: '걸작, 명작'},
      {word: 'amateur', meaning: '아마추어, 비전문가'},
      {word: 'professional', meaning: '프로, 전문가'},
      {word: 'enthusiast', meaning: '열광적인 팬, 애호가'},
      {word: 'pastime', meaning: '취미, 기분 전환'},
      {word: 'recreation', meaning: '휴양, 오락'},
      {word: 'leisure', meaning: '여가, 한가한 시간'},
      {word: 'festival', meaning: '축제, 페스티벌'},
      {word: 'ceremony', meaning: '의식, 기념식'},
      {word: 'tradition', meaning: '전통, 관습'},
      {word: 'heritage', meaning: '(문화적) 유산'},
      {word: 'monument', meaning: '기념비, 역사적 건조물'},
      {word: 'craft', meaning: '공예, 수공업'},
      {word: 'pottery', meaning: '도자기, 도예'},
      {word: 'sculpture', meaning: '조각품, 조각'},
      {word: 'antique', meaning: '골동품의, 골동품'},
      {word: 'box office', meaning: '(극장 등의) 매표소, 흥행 성적'},

      /* 광고, 미디어 & 마케팅 (631~660) */
      {word: 'advertisement', meaning: '광고 (줄여서 ad)'},
      {word: 'commercial', meaning: '(TV·라디오) 상업 광고'},
      {word: 'campaign', meaning: '(홍보·선거 등의) 캠페인'},
      {word: 'target audience', meaning: '핵심 공략 대상, 타깃층'},
      {word: 'brand awareness', meaning: '브랜드 인지도'},
      {word: 'endorsement', meaning: '(유명인의 제품) 홍보, 지지'},
      {word: 'billboard', meaning: '옥외 광고판'},
      {word: 'flyer', meaning: '(홍보용) 전단지'},
      {word: 'brochure', meaning: '안내 책자, 브로슈어'},
      {word: 'slogan', meaning: '슬로건, 광고 문구'},
      {word: 'public relations', meaning: '홍보 활동 (PR)'},
      {word: 'press release', meaning: '보도자료'},
      {word: 'coverage', meaning: '(언론의) 보도, 취재 범위'},
      {word: 'influencer', meaning: '인플루언서, 영향력 있는 사람'},
      {word: 'viral', meaning: '입소문이 난, 바이럴의'},
      {word: 'market share', meaning: '시장 점유율'},
      {word: 'consumer', meaning: '소비자'},
      {word: 'demographic', meaning: '인구통계학적 집단'},
      {word: 'launch', meaning: '(신제품 등을) 출시하다, 시작하다'},
      {word: 'promotional', meaning: '판촉의, 홍보의'},
      {word: 'giveaway', meaning: '무료 증정품, 경품 이벤트'},
      {word: 'sample', meaning: '견본품, 샘플'},
      {word: 'testimonial', meaning: '추천 후기, 고객 체험기'},
      {word: 'catchy', meaning: '기억하기 쉬운, 귀에 쏙 들어오는'},
      {word: 'reach', meaning: '(광고가) 도달하는 범위'},
      {word: 'engagement', meaning: '(고객의) 반응도, 참여도'},
      {word: 'loyalty program', meaning: '단골 우대 프로그램'},
      {word: 'niche market', meaning: '틈새시장'},
      {word: 'mass media', meaning: '대중 매체'},
      {word: 'subscriber', meaning: '구독자'},

      /* 날씨, 계절 & 기후 감각 (661~690) */
      {word: 'forecast', meaning: '일기예보, 예측'},
      {word: 'temperature', meaning: '온도, 기온'},
      {word: 'humidity', meaning: '습도'},
      {word: 'humid', meaning: '습한, 눅눅한'},
      {word: 'drizzle', meaning: '이슬비, 보슬비가 내리다'},
      {word: 'downpour', meaning: '폭우, 억수같이 퍼붓는 비'},
      {word: 'shower', meaning: '소나기'},
      {word: 'thunderstorm', meaning: '뇌우 (천둥 번개를 동반한 비)'},
      {word: 'lightning', meaning: '번개'},
      {word: 'chilly', meaning: '쌀쌀한, 으스스한'},
      {word: 'freezing', meaning: '얼어붙을 듯이 추운'},
      {word: 'scorching', meaning: '타는 듯이 더운, 뙤약볕의'},
      {word: 'breeze', meaning: '산들바람, 미풍'},
      {word: 'gust', meaning: '돌풍, 세찬 바람'},
      {word: 'foggy', meaning: '안개가 낀'},
      {word: 'overcast', meaning: '구름이 잔뜩 낀, 흐린'},
      {word: 'clear up', meaning: '(날씨가) 개다, 맑아지다'},
      {word: 'mild', meaning: '(날씨가) 온화한, 포근한'},
      {word: 'blizzard', meaning: '눈보라'},
      {word: 'hail', meaning: '우박'},
      {word: 'heatwave', meaning: '폭염'},
      {word: 'cold snap', meaning: '꽃샘추위, 갑작스러운 한파'},
      {word: 'frost', meaning: '서리'},
      {word: 'drought', meaning: '가뭄'},
      {word: 'puddle', meaning: '(비 온 뒤) 물웅덩이'},
      {word: 'slippery', meaning: '미끄러운'},
      {word: 'seasonal', meaning: '계절의, 특정 계절에 맞는'},
      {word: 'thaw', meaning: '(눈·얼음이) 녹다'},
      {word: 'gloomy', meaning: '(날씨가) 음산한, 우중충한'},
      {word: 'crisp', meaning: '(공기가) 상쾌하고 시원한'},

      /* 시간, 빈도 & 순서 연결 표현 (691~720) */
      {word: 'eventually', meaning: '결국, 마침내'},
      {word: 'initially', meaning: '처음에는, 시초에'},
      {word: 'gradually', meaning: '점차적으로, 서서히'},
      {word: 'simultaneously', meaning: '동시에'},
      {word: 'meanwhile', meaning: '그동안에, 한편'},
      {word: 'previously', meaning: '이전에, 사전에'},
      {word: 'subsequently', meaning: '그 후에, 뒤이어'},
      {word: 'temporarily', meaning: '일시적으로, 임시로'},
      {word: 'permanently', meaning: '영구적으로'},
      {word: 'occasionally', meaning: '가끔, 때때로'},
      {word: 'rarely', meaning: '드물게, 좀처럼 ~않는'},
      {word: 'seldom', meaning: '거의 ~않는'},
      {word: 'constantly', meaning: '끊임없이, 지속적으로'},
      {word: 'continuously', meaning: '연속적으로, 쉼 없이'},
      {word: 'immediately', meaning: '즉시, 곧바로'},
      {word: 'promptly', meaning: '지체 없이, 신속하게'},
      {word: 'shortly', meaning: '곧, 얼마 안 있어'},
      {word: 'formerly', meaning: '이전에, 예전에'},
      {word: 'lately', meaning: '최근에 (주로 완료형과 함께)'},
      {word: 'nowadays', meaning: '요즘에는, 오늘날에는'},
      {word: 'in the meantime', meaning: '그 사이에, 당분간'},
      {word: 'from time to time', meaning: '때때로, 이따금씩'},
      {word: 'once in a while', meaning: '어쩌다가 한 번'},
      {word: 'ahead of time', meaning: '예정보다 일찍, 미리'},
      {word: 'behind schedule', meaning: '예정보다 늦게'},
      {word: 'on schedule', meaning: '예정대로'},
      {word: 'in advance', meaning: '미리, 사전에'},
      {word: 'punctually', meaning: '시간을 어기지 않고, 정각에'},
      {word: 'for the time being', meaning: '당분간은, 현재로서는'},
      {word: 'all of a sudden', meaning: '갑자기, 느닷없이'}
    ]
  },
  {
    id: 'tos_daily_master_1000_part7',
    emoji: '🤝',
    title: '토스 & 일상 마스터 1000 (Part 7)',
    sub: '회의·협상·시설 관리 + 일상 사물·동작 (721~840)',
    priority: '1000필수',
    pClass: 'p2b',
    type: 'word',
    words: [
      /* 회의, 토론 & 의사결정 (721~750) */
      {word: 'consensus', meaning: '의견 일치, 합의'},
      {word: 'unanimous', meaning: '만장일치의'},
      {word: 'compromise', meaning: '타협하다, 절충안'},
      {word: 'deadlock', meaning: '교착 상태, 막다른 골목'},
      {word: 'proposal', meaning: '제안서, 기획안'},
      {word: 'propose', meaning: '제안하다'},
      {word: 'counterproposal', meaning: '수정 제안, 역제안'},
      {word: 'brainstorm', meaning: '자유롭게 아이디어를 내다'},
      {word: 'minutes', meaning: '(회의의) 의사록, 회의록'},
      {word: 'preside', meaning: '(회의 등의) 사회를 보다, 주재하다'},
      {word: 'adjourn', meaning: '(회의 등을) 잠시 중단하다, 휴회하다'},
      {word: 'reconvene', meaning: '(회의를) 다시 소집하다, 재개하다'},
      {word: 'motion', meaning: '(회의에서의) 동의, 발의'},
      {word: 'second', meaning: '(동의에) 찬성하다, 재청하다'},
      {word: 'vote', meaning: '투표하다, 표결'},
      {word: 'abstain', meaning: '기권하다'},
      {word: 'quorum', meaning: '의사 정족수'},
      {word: 'collaborative', meaning: '협력적인, 공동의'},
      {word: 'counterpart', meaning: '(상대편의) 동등한 위치의 상대방'},
      {word: 'bargaining power', meaning: '협상력, 교섭력'},
      {word: 'concession', meaning: '양보, 인정'},
      {word: 'tentative', meaning: '잠정적인, 시험적인'},
      {word: 'binding', meaning: '(계약 등이) 구속력 있는'},
      {word: 'clause', meaning: '(계약서의) 조항'},
      {word: 'dispute', meaning: '분쟁, 논쟁'},
      {word: 'arbitration', meaning: '중재'},
      {word: 'settlement', meaning: '합의, 해결'},
      {word: 'clarify', meaning: '명확하게 설명하다'},
      {word: 'reiterate', meaning: '(강조하기 위해) 반복해 말하다'},
      {word: 'conclude', meaning: '결론을 내리다, 매듭짓다'},

      /* 건물, 시설, 부동산 & 유지보수 (751~780) */
      {word: 'premises', meaning: '(사업체의) 구내, 부지'},
      {word: 'property', meaning: '부동산, 소유물'},
      {word: 'real estate', meaning: '부동산, 중개업'},
      {word: 'amenity', meaning: '편의 시설 (수영장, 헬스장 등)'},
      {word: 'occupancy', meaning: '(건물 등의) 입주율, 사용'},
      {word: 'evict', meaning: '퇴거시키다, 쫓아내다'},
      {word: 'refurbish', meaning: '재단장하다, 새로 꾸미다'},
      {word: 'remodel', meaning: '개조하다, 리모델링하다'},
      {word: 'demolish', meaning: '(건물을) 철거하다, 허물다'},
      {word: 'hazard', meaning: '위험 요소, 유해물'},
      {word: 'ventilation', meaning: '환기, 통풍'},
      {word: 'plumbing', meaning: '배관 설비'},
      {word: 'insulation', meaning: '단열재, 단열 처리'},
      {word: 'structure', meaning: '구조물, 건축물'},
      {word: 'leakage', meaning: '누출, 깸'},
      {word: 'clog', meaning: '(배수관 등이) 막히다'},
      {word: 'power outage', meaning: '정전'},
      {word: 'blackout', meaning: '대규모 정전'},
      {word: 'generator', meaning: '발전기'},
      {word: 'fire extinguisher', meaning: '소화기'},
      {word: 'emergency exit', meaning: '비상구'},
      {word: 'evacuate', meaning: '대피시키다, 철수하다'},
      {word: 'elevator', meaning: '엘리베이터'},
      {word: 'lobby', meaning: '로비, 현관'},
      {word: 'basement', meaning: '지하실, 지하층'},
      {word: 'attic', meaning: '다락방'},
      {word: 'hallway', meaning: '복도'},
      {word: 'janitor', meaning: '(건물) 관리인, 청소부'},
      {word: 'sanitation', meaning: '위생, 공중위생'},
      {word: 'spacious', meaning: '(공간이) 넓은, 널찍한'},

      /* 일상 생활 사물 & 잡화 (781~810) */
      {word: 'stapler', meaning: '스테이플러 (호치케스)'},
      {word: 'paperclip', meaning: '종이 클립'},
      {word: 'binder', meaning: '바인더, 서류철'},
      {word: 'envelope', meaning: '봉투'},
      {word: 'postage', meaning: '우편 요금'},
      {word: 'stamp', meaning: '우표, 도장'},
      {word: 'scissors', meaning: '가위'},
      {word: 'ruler', meaning: '자'},
      {word: 'tape', meaning: '접착 테이프'},
      {word: 'glue', meaning: '풀, 접착제'},
      {word: 'drawer', meaning: '서랍'},
      {word: 'shelf', meaning: '선반'},
      {word: 'cabinet', meaning: '수납장, 캐비닛'},
      {word: 'wardrobe', meaning: '옷장'},
      {word: 'hanger', meaning: '옷걸이'},
      {word: 'blanket', meaning: '담요'},
      {word: 'pillow', meaning: '베개'},
      {word: 'towel', meaning: '수건'},
      {word: 'mirror', meaning: '거울'},
      {word: 'comb', meaning: '빗, 빗질하다'},
      {word: 'toothbrush', meaning: '칫솔'},
      {word: 'toothpaste', meaning: '치약'},
      {word: 'shampoo', meaning: '샴푸'},
      {word: 'soap', meaning: '비누'},
      {word: 'kettle', meaning: '주전자'},
      {word: 'mug', meaning: '머그잔'},
      {word: 'pot', meaning: '냄비'},
      {word: 'pan', meaning: '프라이팬'},
      {word: 'utensil', meaning: '(주방용) 기구, 도구'},
      {word: 'napkin', meaning: '냅킨, 휴지'},

      /* 신체 부위, 외모 & 물리적 동작 (811~840) */
      {word: 'forehead', meaning: '이마'},
      {word: 'eyebrow', meaning: '눈썹'},
      {word: 'eyelash', meaning: '속눈썹'},
      {word: 'chin', meaning: '턱'},
      {word: 'wrist', meaning: '손목'},
      {word: 'ankle', meaning: '발목'},
      {word: 'elbow', meaning: '팔꿈치'},
      {word: 'shoulder', meaning: '어깨'},
      {word: 'waist', meaning: '허리'},
      {word: 'thigh', meaning: '허벅지'},
      {word: 'calf', meaning: '종아리'},
      {word: 'spine', meaning: '척추, 등뼈'},
      {word: 'posture', meaning: '자세'},
      {word: 'slouch', meaning: '구부정하게 앉다/서다'},
      {word: 'stretch', meaning: '스트레칭하다, 몸을 펴다'},
      {word: 'bend', meaning: '구부리다, 몸을 굽히다'},
      {word: 'twist', meaning: '비틀다, 접지르다'},
      {word: 'lean', meaning: '기울이다, 기대다'},
      {word: 'tiptoe', meaning: '발끝으로 살금살금 걷다'},
      {word: 'stumble', meaning: '발을 헛디디다, 비틀거리다'},
      {word: 'trip', meaning: '발이 걸려 넘어지다'},
      {word: 'slip', meaning: '미끄러지다'},
      {word: 'blink', meaning: '눈을 깜빡이다'},
      {word: 'wink', meaning: '윙크하다'},
      {word: 'frown', meaning: '눈살을 찌푸리다'},
      {word: 'grin', meaning: '활짝 웃다, 씨익 웃다'},
      {word: 'yawn', meaning: '하품하다'},
      {word: 'sneeze', meaning: '재채기하다'},
      {word: 'scratch', meaning: '긁다, 긁힌 자국'},
      {word: 'pinch', meaning: '꼬집다, 집다'}
    ]
  },
  {
    id: 'tos_daily_master_1000_part8',
    emoji: '⚖️',
    title: '토스 & 일상 마스터 1000 (Part 8)',
    sub: '법률·학업 + 일상 슬랭 반응·질감 어휘 (841~960)',
    priority: '1000필수',
    pClass: 'p3b',
    type: 'word',
    words: [
      /* 법률, 규칙, 공공행정 & 보안 (841~870) */
      {word: 'compliance', meaning: '(법규·명령의) 준수, 따름'},
      {word: 'comply', meaning: '(법·명령 등에) 따르다, 준수하다'},
      {word: 'mandate', meaning: '명령하다, 의무화하다'},
      {word: 'mandatory', meaning: '의무적인, 강제적인'},
      {word: 'legislation', meaning: '법률 제정, 법안'},
      {word: 'prohibit', meaning: '금지하다'},
      {word: 'restriction', meaning: '제한, 규제'},
      {word: 'liability', meaning: '법적 책임, 배상 책임'},
      {word: 'lawsuit', meaning: '소송, 고소'},
      {word: 'plaintiff', meaning: '원고 (고소한 사람)'},
      {word: 'defendant', meaning: '피고 (고소당한 사람)'},
      {word: 'verdict', meaning: '(배심원단의) 평결, 판결'},
      {word: 'penalty', meaning: '처벌, 벌칙'},
      {word: 'violation', meaning: '위반, 침해'},
      {word: 'breach', meaning: '(합의·계약의) 위반, 파기'},
      {word: 'confidential', meaning: '기밀의, 비밀의'},
      {word: 'intellectual property', meaning: '지적 재산(권)'},
      {word: 'copyright', meaning: '저작권'},
      {word: 'patent', meaning: '특허, 특허권'},
      {word: 'trademark', meaning: '상표, 트레이드마크'},
      {word: 'fraud', meaning: '사기, 속임'},
      {word: 'scam', meaning: '신용 사기, 사기 치다'},
      {word: 'surveillance', meaning: '감시, 망보기'},
      {word: 'authorize', meaning: '권한을 부여하다, 허가하다'},
      {word: 'unauthorized', meaning: '공인되지 않은, 무단 결재의'},
      {word: 'investigation', meaning: '수사, 조사'},
      {word: 'witness', meaning: '목격자, 증인'},
      {word: 'testimony', meaning: '(법정에서의) 증언'},
      {word: 'jurisdiction', meaning: '사법권, 관할권'},
      {word: 'enforce', meaning: '(법률 등을) 집행하다, 강제하다'},

      /* 학업, 교육, 시험 & 연구 (871~900) */
      {word: 'curriculum', meaning: '교육과정, 커리큘럼'},
      {word: 'syllabus', meaning: '강의 계획서'},
      {word: 'tuition', meaning: '수업료, 등록금'},
      {word: 'scholarship', meaning: '장학금'},
      {word: 'faculty', meaning: '(대학의) 교수진, 교직원'},
      {word: 'assignment', meaning: '과제, 숙제'},
      {word: 'dissertation', meaning: '(학위) 논문'},
      {word: 'plagiarism', meaning: '표절, 도용'},
      {word: 'enroll', meaning: '등록하다, 입학하다'},
      {word: 'drop out', meaning: '중퇴하다, 자퇴하다'},
      {word: 'graduate', meaning: '졸업하다, 졸업생'},
      {word: 'undergraduate', meaning: '대학생, 학부생'},
      {word: 'postgraduate', meaning: '대학원생'},
      {word: 'major', meaning: '전공하다, 주전공'},
      {word: 'minor', meaning: '부전공하다, 부전공'},
      {word: 'semester', meaning: '학기'},
      {word: 'lecture', meaning: '강의, 강연'},
      {word: 'experiment', meaning: '실험, 실험하다'},
      {word: 'hypothesis', meaning: '가설 (복수: hypotheses)'},
      {word: 'analysis', meaning: '분석'},
      {word: 'finding', meaning: '(연구·조사의) 결과, 결론'},
      {word: 'peer review', meaning: '동료 심사, 전문가 검토'},
      {word: 'academic', meaning: '학업의, 학술적인'},
      {word: 'literacy', meaning: '문해력, 읽고 쓰는 능력'},
      {word: 'cram', meaning: '(시험 직전에) 벼락치기하다'},
      {word: 'transcript', meaning: '성적 증명서'},
      {word: 'diploma', meaning: '졸업장, 수료증'},
      {word: 'field trip', meaning: '현장 학습, 견학'},
      {word: 'laboratory', meaning: '실험실, 연구소'},
      {word: 'scholar', meaning: '학자'},

      /* 현지 10대·일상 구어 반응 & 메신저 슬랭 (901~930) */
      {word: 'legit', meaning: '진짜인, 찐인, 제대로인 (legitimate 줄임말)'},
      {word: 'cringe', meaning: '오글거리는, 민망해서 움츠러드는'},
      {word: 'vibe', meaning: '느낌, 분위기'},
      {word: 'hyped', meaning: '엄청 신난, 기대감에 부푼'},
      {word: 'bummed', meaning: '실망한, 낙담한 (bummed out)'},
      {word: 'clout', meaning: '(SNS상의) 영향력, 인기'},
      {word: 'shady', meaning: '수상쩍은, 구린내가 나는'},
      {word: 'salty', meaning: '(사소한 일에) 삐친, 억울해하는'},
      {word: 'flex', meaning: '자랑하다, 뽐내다'},
      {word: 'ghost', meaning: '(연락을) 읽씹하고 잠수타다'},
      {word: 'roast', meaning: '뼈 때리다, 대놓고 디스하다'},
      {word: 'ditch', meaning: '(친구·약속을) 바람맞히다, 팽개치다'},
      {word: 'catchy', meaning: '귀에 맴도는, 중독성 있는'},
      {word: 'sketchy', meaning: '어딘가 미심쩍은, 엉성한'},
      {word: 'chill', meaning: '느긋하게 놀다, 쿨한'},
      {word: 'slock', meaning: '대충 만든 엉터리 제품, 싸구려'},
      {word: 'banger', meaning: '(노래·영화가) 완전 띵곡/대박작'},
      {word: 'goofy', meaning: '얼빠진 듯 웃긴, 엉뚱한'},
      {word: 'tacky', meaning: '촌스러운, 조잡한'},
      {word: 'corny', meaning: '진부한, 유치해서 오글거리는'},
      {word: 'wholesome', meaning: '마음이 따뜻해지는, 훈훈한'},
      {word: 'lowkey', meaning: '은근히, 대놓고는 말고 살짝'},
      {word: 'highkey', meaning: '완전 대놓고, 진짜 진심으로'},
      {word: 'mood', meaning: '완전 내 심정, 개공감 (메신저 리액션)'},
      {word: 'slay', meaning: '완전 찢었다, 대박 잘 해내다'},
      {word: 'clueless', meaning: '아무것도 모르는, 멍청한'},
      {word: 'lame', meaning: '노잼인, 시시한'},
      {word: 'epic', meaning: '대서사시급의, 개쩌는'},
      {word: 'gross', meaning: '역겨운, 징그러운'},
      {word: 'neat', meaning: '깔끔한, 솜씨가 좋은, 멋진'},

      /* 질감, 모양 & 물리적 상태 묘사 (931~960) */
      {word: 'rough', meaning: '거친, 올록볼록한'},
      {word: 'smooth', meaning: '매끄러운, 부드러운'},
      {word: 'sticky', meaning: '끈적거리는, 달라붙는'},
      {word: 'slippery', meaning: '미끄러운'},
      {word: 'fluffy', meaning: '폭신폭신한, 솜털 같은'},
      {word: 'fuzzy', meaning: '보송보송한, 솜털이 덮인'},
      {word: 'slimy', meaning: '미끈거리는, 진득한'},
      {word: 'greasy', meaning: '기름때 묻은, 미끌미끌한'},
      {word: 'damp', meaning: '축축한, 눅눅한'},
      {word: 'soaked', meaning: '물에 흠뻑 젖은'},
      {word: 'dry', meaning: '건조한, 마른'},
      {word: 'coarse', meaning: '(모래·천 등이) 거친, 굵은'},
      {word: 'stiff', meaning: '뻣뻣한, 굳은'},
      {word: 'flexible', meaning: '잘 구부러지는, 탄력 있는'},
      {word: 'fragile', meaning: '깨지기 쉬운, 부서지기 쉬운'},
      {word: 'sturdy', meaning: '견고한, 튼튼한'},
      {word: 'rusty', meaning: '녹슨, (실력이) 녹슨'},
      {word: 'sharp', meaning: '날카로운, 뾰족한'},
      {word: 'dull', meaning: '무딘, 둔탁한, 재미없는'},
      {word: 'blunt', meaning: '뭉툭한, 날이 안 선'},
      {word: 'transparent', meaning: '투명한'},
      {word: 'opaque', meaning: '불투명한'},
      {word: 'hollow', meaning: '속이 텅 빈'},
      {word: 'solid', meaning: '단단한, 속이 꽉 찬'},
      {word: 'dense', meaning: '밀도가 높은, 빽빽한'},
      {word: 'hazy', meaning: '흐릿한, 아지랑이가 낀'},
      {word: 'sparkling', meaning: '반짝거리는, 스파클링의'},
      {word: 'dusty', meaning: '먼지가 자욱한'},
      {word: 'smudged', meaning: '(유리·화면 등이) 얼룩진'},
      {word: 'wrinkled', meaning: '주름진, 구겨진'}
    ]
  },
  {
    id: 'tos_daily_master_1000_part9',
    emoji: '🏁',
    title: '토스 & 일상 마스터 1000 (Part 9 - 완결)',
    sub: '고급 논리 전개 부사 + 핵심 완결 구동사 (961~1000)',
    priority: '1000완료',
    pClass: 'p4b',
    type: 'word',
    words: [
      /* Part 5 논리 연결, 양보 & 대조 접속부사 (961~980) */
      {word: 'furthermore', meaning: '뿐만 아니라, 더욱이'},
      {word: 'moreover', meaning: '게다가, 더욱이'},
      {word: 'nevertheless', meaning: '그럼에도 불구하고'},
      {word: 'nonetheless', meaning: '그렇기는 하지만, 그래도'},
      {word: 'consequently', meaning: '결과적으로, 그에 따라'},
      {word: 'therefore', meaning: '그러므로, 따라서'},
      {word: 'accordingly', meaning: '그에 맞춰서, 부응하여'},
      {word: 'in contrast', meaning: '그에 반해서, 대조적으로'},
      {word: 'conversely', meaning: '역으로, 반대로 말하면'},
      {word: 'likewise', meaning: '마찬가지로, 비슷하게'},
      {word: 'similarly', meaning: '유사하게, 마찬가지로'},
      {word: 'specifically', meaning: '구체적으로 말해서, 특히'},
      {word: 'namely', meaning: '즉, 다시 말해'},
      {word: 'incidentally', meaning: '그런데, 말이 나온 김에'},
      {word: 'notably', meaning: '특히, 현저하게'},
      {word: 'ultimately', meaning: '궁극적으로, 결국에는'},
      {word: 'presumably', meaning: '아마도, 짐작건대'},
      {word: 'undoubtedly', meaning: '의심할 여지 없이, 확실히'},
      {word: 'inevitably', meaning: '불가피하게, 필연적으로'},
      {word: 'in essence', meaning: '본질적으로, 요약하자면'},

      /* 일상 & 토스 핵심 완결 구동사 (981~1000) */
      {word: 'wrap up', meaning: '(회의·일·프로젝트를) 끝마치다, 마무리 짓다'},
      {word: 'follow up', meaning: '(이전 일의 경과를) 후속 조치하다, 확인하다'},
      {word: 'back up', meaning: '(주장 등을) 뒷받침하다, 백업하다'},
      {word: 'sort out', meaning: '(문제·혼란을) 해결하다, 정리하다'},
      {word: 'opt for', meaning: '(여러 대안 중) ~을 선택하다'},
      {word: 'rely on', meaning: '~에 의지하다, 신뢰하다'},
      {word: 'point out', meaning: '(오류나 사실을) 지적하다, 짚어내다'},
      {word: 'look into', meaning: '(원인이나 사안을) 조사하다, 살펴보다'},
      {word: 'take over', meaning: '(역할·기업 등을) 인수하다, 넘겨받다'},
      {word: 'step down', meaning: '(직위·자리에서) 물러나다, 사퇴하다'},
      {word: 'set up', meaning: '(장비·모임을) 준비하다, 마련하다'},
      {word: 'phase out', meaning: '(노후 모델·정책을) 단계적으로 폐지하다'},
      {word: 'iron out', meaning: '(작은 문제점이나 갈등을) 다듬어 해결하다'},
      {word: 'scale up', meaning: '(규모·생산을) 확대하다'},
      {word: 'bounce back', meaning: '(슬럼프·충격에서) 다시 회복하다'},
      {word: 'stand out', meaning: '(눈에 띄게) 두드러지다, 출중하다'},
      {word: 'narrow down', meaning: '(선택지 범위를) 좁히다'},
      {word: 'bring about', meaning: '(변화·결과를) 초래하다, 야기하다'},
      {word: 'keep up with', meaning: '(시대 변화나 속도를) 따라잡다, 뒤처지지 않다'},
      {word: 'rule out', meaning: '(가능성이나 후보에서) 배제하다, 제외하다'}
    ]
  }
];

/* ─── TOEIC PART UI ──────────────────────────────────── */
const PART_INFO={
  all:{label:'전체',sub:'파트2~5 전체'},
  p2:{label:'파트 2',sub:'사진 묘사'},
  p3:{label:'파트 3',sub:'만능문장'},
  p4:{label:'파트 4',sub:'유형별 템플릿'},
  p5:{label:'파트 5',sub:'만능문장'},
};
