const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const Core=require('../js/core.js');
const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../js/data.js'),'utf8')+'\nthis.DATA={TOEIC_PARTS,CUSTOM_CARDS};',context);
const {TOEIC_PARTS,CUSTOM_CARDS}=context.DATA;
const counts=Object.fromEntries(Object.entries(TOEIC_PARTS).map(([k,v])=>[k,v.length]));
assert.deepEqual(counts,{p2:73,p3:42,p4:29,p5:50});assert.equal(Object.values(counts).reduce((a,b)=>a+b),194);
assert.equal(CUSTOM_CARDS.filter(c=>c.type==='word').length,10);assert.equal(CUSTOM_CARDS.filter(c=>c.type==='mistake').length,1);assert.equal(CUSTOM_CARDS.filter(c=>c.type==='sent').length,0);
const base={words:[{word:'Lead',meaning:'이끌다'},{word:'lead',meaning:'납'}],sents:[],toeicParts:TOEIC_PARTS,customCards:CUSTOM_CARDS};
const a=Core.buildCatalog(base),b=Core.buildCatalog({...base,words:[{word:'new',meaning:'새로운'},...base.words].reverse()});
for(const item of a.items)assert.ok(b.items.some(x=>x.canonicalKey===item.canonicalKey&&x.id===item.id),'stable ID');
assert.notEqual(a.items.find(i=>i.ko==='이끌다').id,a.items.find(i=>i.ko==='납').id);
const duplicate=Core.buildCatalog({words:[{word:'stroll',meaning:'한가롭게 거닐다, 산책하다'}],customCards:CUSTOM_CARDS});
assert.equal(Core.selectItems(['mine_words','vocab_core140'],duplicate).filter(i=>i.en==='stroll').length,1);
const p3=Core.selectItems(['toeic_p3'],a),p4=Core.selectItems(['toeic_p4'],a),wrong=p3[0];const progress={[wrong.id]:{state:'review',lapses:2,dueAt:0}};
assert.equal(Core.selectItems(['toeic_p4'],a,progress).some(i=>i.id===wrong.id),p4.some(i=>i.id===wrong.id));
const state={progress:{},events:[]};Core.recordStudyEvent(state,{itemId:wrong.id,sourceIds:['toeic_p3'],mode:'speak',correct:true,ts:new Date(2026,9,2,12).getTime()});
assert.deepEqual(Core.selectTodayStats(state.events,'2026-10-02'),{attempts:1,correct:1,accuracy:100,uniqueItems:1});
const before=a.items.find(i=>i.en==='lead'&&i.ko==='납').id;const after=Core.buildCatalog({...base,words:[base.words[1]]});assert.equal(after.items.find(i=>i.en==='lead'&&i.ko==='납').id,before);assert.equal(progress[wrong.id].lapses,2);
const fakeStorage=(()=>{const m=new Map([['vm-words',JSON.stringify(base.words)],['vm-errCount',JSON.stringify({1:2})]]);return{get length(){return m.size},key:i=>[...m.keys()][i],getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}})();
const userCatalog=Core.buildCatalog(base),report=Core.migrationReport(fakeStorage,userCatalog,{words:base.words,sents:[],errCount:{1:2},sErrCount:{}});assert.ok(report.backedUp>=2);assert.ok(fakeStorage.getItem('vm-backup-v1-words'));const migrated=JSON.parse(fakeStorage.getItem('vm-progress-v2'));assert.equal(Object.keys(migrated).length,1);
const envelope=Core.exportEnvelope(userCatalog,{progress:migrated,events:[]},{sourceIds:['mine_words'],mode:'flash'}),inspection=Core.inspectImport(JSON.stringify(envelope),userCatalog);assert.equal(inspection.valid,true);assert.equal(inspection.conflictCount,0);
const malicious=Core.buildCatalog({words:[{word:'<img onerror=alert(1)>',meaning:'test'}]});assert.equal(malicious.items[0].en,'<img onerror=alert(1)>');assert.ok(!JSON.stringify(malicious).includes('<img src='));
const repository=new Core.LocalStorageRepository(fakeStorage);repository.saveSnapshot({progress:migrated,events:state.events,selection:{sourceIds:['mine_words'],mode:'flash'}});
const exported=repository.exportJson(userCatalog),preview=repository.previewImport(exported,userCatalog);assert.equal(preview.valid,true);
repository.saveSnapshot({progress:{},events:[],selection:null});const restored=repository.applyImport(preview,userCatalog);assert.equal(Object.keys(restored.progress).length,Object.keys(migrated).length);assert.equal(restored.events.length,1);assert.deepEqual(restored.selection,{sourceIds:['mine_words'],mode:'flash'});
const brokenStorage=(()=>{const m=new Map();let writes=0;return{getItem:k=>m.get(k)??null,setItem:(k,v)=>{if(++writes===2)throw new Error('quota');m.set(k,String(v));},removeItem:k=>m.delete(k)}})();assert.throws(()=>new Core.LocalStorageRepository(brokenStorage).saveSnapshot({progress:{a:1},events:[],selection:null}),/quota/);assert.equal(brokenStorage.getItem('vm-progress-v2'),null);
console.log('14 core checks passed');
